### ISSUE TITLE
Alter incoming data

### ISSUE THREAD

**Issue by zzolo** [tangrams/tangram#123]
I am just digging into this awesome project, so I may have missed something.  But I was wondering if there is an event or some other way to alter the vector tiles as they come in?  Specifically I would like to combine some data that is not in OSM.

Many thanks!

**Comment by meetar** [comment]
You should be able to use multiple vector tile sources now – what kinds of datasets are you working with, and how are you thinking you'd like to combine them?

**Comment by zzolo** [comment]
Yep, totally able to pull in multiple data sources.

I have some building data that I would like to alter/replace the OSM buildings that are there now.  Not entirely sure how I plan on reconciling the data, just looking for a place to do that.

**Comment by meetar** [comment]
Right – that's something we're looking at too. Currently the only way to do that is to alter the datasets to fit together the way you'd like, but we hope to add the ability to filter features by "id" soon – in that case you could specify a style on the OSM layer which filters out the buildings you wanted to hide, and then bring the other dataset in on top of it.

I'll drop a link to a demo in this thread when we get it working. Thanks for the feedback!

**Comment by zzolo** [comment]
Thanks for the help and speediness.  That does sound interesting and could come close to what we need.

But I actually do want to alter the datasets as they come in.  The data comes in through the vector tiles (JSON) and that gets rendered.  What I am looking for is a way to alter that JSON before it gets rendered (in the client, not the server).  This would either be an event or a function to pass, or there is no hook and I just have to hack it together.

**Comment by bcamper** [comment]
There's nothing right now, but we do plan to add event hooks like that. I'm hesitant to add it too quickly without thinking through the API, but it should be doable soon. Right now we are just trying to lock down the API for a first 0.1 release :)

**Comment by zzolo** [comment]
No worries.  I kind of thought that might be the case; the project is really amazing and really new.  If you have an idea of where a good place might be to hack it in for my purposes, that would be helpful.  Thanks again for everything.

**Comment by duhaime** [comment]
@bcamper @meetar Hi all, I'm also super impressed with the work you're doing on this project, and in a position similar to that of @zzolo. Essentially, I'm wanting to give specific buildings specific colors, and I thought in order to achieve this effect I'd add an attribute on the incoming building data, then use that attribute to set the fill value for the given building.

Are there any hooks in place now for adding attributes to buildings, or to identify buildings by any kind of identifiers? I wanted to ask because the topojson doesn't seem to give any kind of ids for the buildings:

```
// url: https://tile.mapzen.com/mapzen/vector/v1/all/13/4095/2725.topojson?api_key=WOOHOO

"buildings": {
      "type": "GeometryCollection",
      "geometries": [
        {
          "type": "MultiPolygon",
          "properties": {
            "kind": "building",
            "area": 25636,
            "sort_rank": 475,
            "kind_detail": "college",
            "source": "openstreetmap.org",
            "min_zoom": 13.0,
            "landuse_kind": "residential",
            "scale_rank": 3
          },
          "arcs": [
            [
              [
                2
              ]
            ],
            [
              [
                3
              ]
            ],
            [
              [
                4
              ]
            ]
          ]
        },
```
If there are now ways to identify buildings, or if there are better ways to color buildings on an individual basis, I'd be very thankful for any insights you can offer. Either way, thanks for this awesome work!

**Comment by bcamper** [comment]
@duhaime the building data in Mapzen vector tiles will include ids for individual buildings at higher zooms (z15+), and at lower zooms (z13-14), some prominent buildings will include individual ids, while others may be coalesced into larger polygons (for rendering performance).

You can hover on individual buildings here to get an idea of what is included (zoom in/out to compare):
https://tangrams.github.io/explorer/#16.8/40.7214/-73.9948//

Docs here:
https://mapzen.com/documentation/vector-tiles/layers/#buildings-and-addresses

You *can* add fields to the incoming data via the data source [`transform` option](https://mapzen.com/documentation/tangram/sources/#transform), however depending on what you are trying to do, the more natural approach may be to just use feature-specific styling (with JS functions, for example), to color or otherwise style your buildings.

**Comment by duhaime** [comment]
@bcamper Holy moly this is awesome news. Yes, I was planning to use a custom `color` function in the `draw` attribute of the `building` layer in my style file, but just needed to find a way to connect the dots between the intended building styles and the building data I was seeing. It looks like the Mapzen vector tiles will allow me to look up a given building's styles perfectly.

Thanks so much for the quick response!
