### ISSUE TITLE
Smooth transition when zooming

### ISSUE THREAD

**Issue by Hywan** [tangrams/tangram#158]
Hello :-),

Thanks for this great piece of code!
Nevertheless, is it possible to avoid to “repaint” the whole map when we zoom and have a smooth transition between 2 zoom levels instead? Like Mapbox GL does for instance.

Thanks :-).

**Comment by bcamper** [comment]
Hi - I would like to do this as well, but it requires a little more research. There are two versions of Leaflet the library is compatible with:

- 0.7.x (current prod release): I'm not sure it's possible to implement smooth zoom for Tangram with this version, because Leaflet uses CSS transitions to zoom the map elements, but this cannot be applied to a WebGL context. Since this version also does not support fractional zoom levels, I'm not sure what to do here.
- 1.x (unreleased, next major release): The next version of Leaflet (used by the demo bundled with this repo) supports fractional zoom. It may still use CSS transitions for regular zooms (can't remember, need to check), but it also has new functions like `map.flyTo()` that allow you to animate smoothly across a range of zoom levels. As Leaflet 1.x becomes an official release, we will likely revisit this issue.

Thanks for your interest and let us know if you have any more questions!

**Comment by Hywan** [comment]
Anyway to be kept informed (maybe Twitter or if I watch this repository)?

**Comment by Hywan** [comment]
(forget to say thank you for the answer!)

**Comment by bcamper** [comment]
Certainly, I recommend watching this repository, and we also have a new twitter account at http://twitter.com/tangramjs, where we will post about new releases.

**Comment by Hywan** [comment]
Do you have a list of “entry contributions”?

**Comment by Hywan** [comment]
@bcamper Any good news :-)?

**Comment by meetar** [comment]
@Hywan Hi Evan – Thanks for your continued interest! We still plan to implement this in the future, but we don't have a deadline for it… we'll be sure to mention it in the release notes when we do.

And we don't have a list of "“entry contributions”, although that's a good idea!

**Comment by Hywan** [comment]
@meetar Thanks!
