### ISSUE TITLE
Point Matching inside Polygon

### ISSUE THREAD

**Issue by igaln** [tangrams/tangram#193]
Is it possible to doa filter where we can check if a point is inside the polygon,
something like POSTGIS ST_Contains,

I tried the filter function, but it does not reveals the geometry parameter of the json, so could not do any operations there.

**Comment by nvkelso** [comment]
What are you trying to do, why do you need point in polygon test?

Have you tried turf.js? It should integrate.

**Comment by igaln** [comment]
I am trying to sort/filter layers in Tangram (topojson from mapzen lets say street, or building data) by matches through custom geo location data from user content. 

Turf.js looks great, I will give it a shot. Thank you!

**Comment by igaln** [comment]
@nvkelso would there be a way to import turf into scene .yaml filters?
or directly pass a geojson to Tangram scene?

I am trying filter road data with matching points (ex, only draw roads that match x points), currently I have to do manual initialization to calculate the matching data with turf, then create a filter and reupdate the scene.

**Comment by meetar** [comment]
That's how I would do it too – and if I understand the problem correctly
that's the only way I can think of for turf.js to interact with the scene,
although you may be able to streamline your process depending on your
specific goals. For instance, the Tangram JavaScript API does allow you to
pass geojson to the scene by adding it as a new data source.

**Comment by igaln** [comment]
thanks @meetar I was looking for a way to directly pass a geojson object, rather than a URL as a data source, but havent found anything yet. I am digging into GeoJSONTileSource.

**Comment by igaln** [comment]
just to clarify, I can just draw the data using Leaflet as a different layer.
I am somehow really liking the flow of Tangram, and trying to merge geo operations inside Yaml function scope.

**Comment by bcamper** [comment]
Hey @igaln, thanks for trying out Tangram! We'll get back to you soon with an example -- the kind of thing you're trying to do with incorporating geometry transforms is something we're interested in, but haven't spent a lot of time on yet. However, we have had one past pull request along these lines (https://github.com/tangrams/tangram/pull/125), and I can put together a small demo of how that works.

To clarify: we actually don't have a way of dynamically loading new source data at runtime via JS right now (though that is something we plan to add soon, and is already supported by our native C++ version, github.com/tangrams/tangram-es). However, as discussed in the PR above, we do have a way to incorporate external libraries like Turf for additional processing. It is a little trickier than simply including those files in your HTML like a traditional web page, because all the data processing in Tangram happens inside [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API). So those external scripts have to be specified in the YAML, and then loaded by Tangram itself into the web workers. However, we have gotten it to work, so it is possible :)

**Comment by igaln** [comment]
@bcamper thank you!
I am porting this project (https://vimeo.com/108400134  which was built in 2008) to Tangram,
very excited to use shaders and map data together. 

will also look into -es port soon to see. all great stuff.

**Comment by bcamper** [comment]
Let us know if/when you have more questions or feedback. Good luck!
