### ISSUE TITLE
Demo not working in Chrome

### ISSUE THREAD

**Issue by metamn** [tangrams/tangram#203]
Hello guys,

Very nice work indeed ... you are coming from the future.

I've downloaded the demo which works excellent in FF not at all in Chrome. Tested on Ubuntu 14.04 and Android 4.2.2 all with latest versions for both browsers.

Please check the console output screenshot.
![screenshot from 2015-10-21 17 33 08](https://cloud.githubusercontent.com/assets/86295/10639720/5470ba5c-781a-11e5-8cfc-0f493cdf3e05.png)

**Comment by metamn** [comment]
The complete console log:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
Uncaught ReferenceError: MPZN is not defined
XMLHttpRequest cannot load file:///home/cs/Downloads/tangram-master/demos/scene.yaml?1445438287653. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
Tangram v0.3.3: Scene.load() failed to load demos/scene.yaml: There was a network error[object XMLHttpRequestProgressEvent] Error: There was a network error[object XMLHttpRequestProgressEvent]
    at Error (native)
    at XMLHttpRequest.request.onerror (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:36972:20)
    at file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:36977:17
    at Object.Utils.io (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:36956:19)
    at file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:37000:19
    at Object.Utils.loadResource (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:36998:12)
    at Object.loadSceneRecursive (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:29444:22)
    at Object.loadScene (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:29426:28)
    at Scene.loadScene (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:28962:36)
    at Scene.load (file:///home/cs/Downloads/tangram-master/dist/tangram.debug.js:27989:29)
```

**Comment by bcamper** [comment]
Hi @metamn -- it looks like you are running the demo locally. To help debug:

1. Can you let us know if the hosted demo works for you: http://tangrams.github.io/tangram

2. From your log, it looks like a Cross-Origin Resource Sharing (CORS) issue (on this file: `file:///home/cs/Downloads/tangram-master/demos/scene.yaml`). This makes sense, because Chrome doesn't support CORS requests for locally served files (this info is buried in that log message in your screenshot). To rectify this, try running the install and make instructions (e.g. `npm install && make`), followed by starting a local web server (e.g. so you are loading the demo from a local port such as `http://localhost:8000`), as described here: https://github.com/tangrams/tangram/blob/master/CONTRIBUTING.md

Please give that a try and let us know if it works. Thanks!

**Comment by metamn** [comment]
Oh ... CORS ... tested the hosted demo and all's fine :)

Thanks a lot!

**Comment by bcamper** [comment]
Great.
