### ISSUE TITLE
Worker-based architecture.

### ISSUE THREAD

**Issue by trusktr** [tangrams/tangram#207]
Is there some design documents on how you guys are using web workers? I'm curious to know in order to learn and develop my skills using workers for rendering-related tasks. If there are no architecture docs, mind explaining here the basic concepts?

Some members of the web community are working on a rendering project at http://infamous.io (discussing and planning at http://forums.infamous.io). Thanks!

EDIT: Funny thing, I'm also using something called a SceneWorker in [my prototype](https://github.com/infamous/motor/blob/joe/src/core/SceneWorker.js). Nothing renders yet though, I'm getting there. :}

EDIT: I was thinking of doing something similar to the WorkerBroker concept you have, and calling methods on workers. It's similar to RPC over network, but between workers instead. The difference with my idea is that instead of passing the method name into the postMessage call, I'd like to just make methods on the worker, so f.e. `worker.someMethod(arg1, arg2, etc)`.

**Comment by meetar** [comment]
Hello @trusktr!

We don't have any public design documents about the workers, but the general idea is that each worker makes a tile request and filters and styles the data according to the scene file styling rules. Then it constructs 3D geometry and packages it into WebGL binary buffers which are transferred back to the main thread.

This results in good performance, but has some limitations, especially in situations when we'd like screen-wide or cross-tile features, because the workers don't know about anything outside their own tile. In the future, we may consider an API which does more cross-thread coordination behind the scenes.

**Comment by trusktr** [comment]
@meetar Interesting! Do you have any performance results that might compare worker vs non-worker implementations? I'm curious to get an idea (specifically a real-world-example) of how workers can help performance.
