### ISSUE TITLE
Buildings don't always fill with v0.4

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#210]
Browsing around Washington DC I'm seeing tons of buildings that don't fill (but do stroke) at mid zooms. Zooming into high (neighborhood) zooms they do fill. And sometimes the interior ring (that shouldn't be filled) is filling in at high zooms.

Howard University in DC with **v0.4 Tangram** shows outline only buildings (a regression):

<img width="732" alt="screen shot 2015-11-03 at 21 40 07" src="https://cloud.githubusercontent.com/assets/853051/10930498/852fad48-8273-11e5-912c-7f3fbec4e2f8.png">

Howard University in DC with **v0.3 Tangram** draws fill properly:

<img width="633" alt="screen shot 2015-11-03 at 21 39 44" src="https://cloud.githubusercontent.com/assets/853051/10930499/854d8fca-8273-11e5-9183-ac09f1e4ecfb.png">

Elsewhere in DC...

Note the Thomas Jefferson Memorial outer ring not filling. Same for Library of Congress.

<img width="1176" alt="screen shot 2015-11-03 at 20 11 24" src="https://cloud.githubusercontent.com/assets/853051/10930470/47fcfe94-8273-11e5-827f-a09f60bc3130.png">

<img width="1151" alt="screen shot 2015-11-03 at 20 11 16" src="https://cloud.githubusercontent.com/assets/853051/10930472/4816c6a8-8273-11e5-961d-9b5c5e3acb70.png">

<img width="1086" alt="screen shot 2015-11-03 at 20 10 59" src="https://cloud.githubusercontent.com/assets/853051/10930471/4815fb24-8273-11e5-8dfc-cc4967f084cb.png">

**Comment by nvkelso** [comment]
See: http://nvkelso.github.io/tangram-skin-and-bones/#15/38.9237/-77.0191

**Comment by blair1618** [comment]
I think this may be a styling error. In the buildings layer [here](https://github.com/nvkelso/tangram-skin-and-bones/blob/gh-pages/scene.yaml#L2790), `order` is specified as a series of stops. This isn't currently supported, as described in the [docs](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#order), so the polygons that get this rule will not be drawn. 

This behavior for invalid orders is new in v0.4. In previous versions, geometries without valid orders would be placed somewhere between orders 0 and 1, but that effect is due to some undefined behavior and can't be relied upon (or reproduced in tangram-es), so we've changed the behavior to make it more clear that the geometry has invalid styling. 

@bcamper will know whether or not I'm reasoning correctly about this

**Comment by meetar** [comment]
@blair1618 has it right – changing order to  a simple integer value fixed this for me.

**Comment by bcamper** [comment]
@blair1618 is correct, I was just summarizing the same. However, I need to add even more `order` enforcement (probably for 0.4.1), in this case it was mostly "luck", I removed some dead order code in 0.4 and that changed the code path.

**Comment by meetar** [comment]
(Supporting stops in a `order` parameter is an interesting idea though!)

**Comment by bcamper** [comment]
Logged that feature addition here: https://trello.com/c/nWfxK3x6/713-support-stop-interpolation-for-order
