### ISSUE TITLE
Recalc resolution with retina/not-retina display change

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#211]
When I detach from my not-retina display, the Tangram map appears low-quality on my retina Macbook display. It should detect the change and "reload" to be retina.

When I attach my not-retina display, the Tangram map seems to perform fine, though?

Tested with Tangram v0.4

**Comment by bcamper** [comment]
Right, it assumes that your device pixel ratio won't change once set (didn't really think about this as a likely scenario at the time). So it's keeping the same resolution throughout. It only "works" going from high to low density because it's continuing to render at 2x the actual screen resolution!

We could check the pixel ratio in the render loop to see if it has changed, let me take a look.

**Comment by bcamper** [comment]
Need to test on real hardware, but should be resolved by https://github.com/tangrams/tangram/commit/1518fdb1b0a2087615c83627d17a22ff2d01b531

**Comment by bcamper** [comment]
Note: also need to add an explicit `scene.rebuild()` because pixel density ripples through sprite + text rendering.

**Comment by bcamper** [comment]
https://github.com/tangrams/tangram/commit/43ef686b14c6a49c19919e4dcb65857ada858b65

**Comment by bcamper** [comment]
Added in 0.4.1
