### ISSUE TITLE
run Demo  on local machine without local server  

### ISSUE THREAD

**Issue by harshdeep1230** [tangrams/tangram#228]
Hi.
Is that any way to run demo on local machine without local server .Its is giving the following error 

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Thanking you in advance

**Comment by bcamper** [comment]
Hi -- unfortunately due to web browsers' [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) security rules, it is not possible to run the demo from the local file system without a web server. For this reason we recommend using either the `python -m SimpleHTTPServer` command, or a similar alternative such as [http-server](https://github.com/indexzero/http-server) for node.js. Let us know if you have any issues with that approach.

**Comment by harshdeep1230** [comment]
Hi.
i have one demo of tangram (example) and then i am try to use with phone gap android. In phone gap we just put the js ,css  and html in android  and load the index.html page and in this yaml file not working .So how it is possible in android phone gap without server

**Comment by bcamper** [comment]
Interesting, we haven't had any inquires about that use case before, but I can see how it makes sense for  completely embedded/contained environments.

I suggest you put your scene file YAML into a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) (as is common for embedding images in CSS), which you can then use directly as your scene file URL when initializing Tangram.

There are converters such as http://dataurl.net/ and http://dopiaza.org/tools/datauri/index.php.

I tried this with a simple proof of concept and it worked (I did encounter some UTF-8 encoding issues when I used a much more complex scene YAML that included non-Roman characters, though from some quick reading this appears to be a general issue with data URI base64 encoding and UTF-8).

Give that a try and let us know how it goes.

Thanks,
Brett
