### ISSUE TITLE
Add synthetic label positions for non-tiled polygons

### ISSUE THREAD

**Issue by burritojustice** [tangrams/tangram#243]
Importing the transitland operator polygons and used labels text visible:true -- seeing text at many strange positions rather than one central position.

http://tangrams.github.io/tangram-play/?scene=https://gist.githubusercontent.com/anonymous/78d5327116ac44d26a07/raw/50bfb7e5b086a2697c6b1ccbe5fe97fff12dec13/transitland-operators.yaml#10/41.4556/-72.7487

![image](https://cloud.githubusercontent.com/assets/3979711/12965723/3ae8c0ca-d00d-11e5-820a-e309ca8d5859.png)

**Comment by bcamper** [comment]
Thanks. I hadn't thought of that, but yes it would be possible to derive label positions (centroids or weighted in some other manner) from the original non-tiled data source. It's not happening now because the data has already been tiled client-side (by geojson-vt) by the time the Tangram styling pipeline is applied. I'll leave this ticket open to explore this in the future though.

**Comment by bcamper** [comment]
cc @blair1618 for future consideration

**Comment by bcamper** [comment]
Closed via #302
