### ISSUE TITLE
Scene.load() failed to load scene.yaml

### ISSUE THREAD

**Issue by matbeard** [tangrams/tangram#251]
I'm trying to incorporate a Tangram layer into an existing project, but I'm experiencing the above issue.

The full error is: Tangram v0.4.6: Scene.load() failed to load /css/scene.yaml: Can't load worker because couldn't find base URL that library was loaded from

The web server is IIS 10. I've had to add a mimetype for .yaml files (I was getting 404 errors before doing that). Any ideas what's causing this error?

**Comment by matbeard** [comment]
I've switched to loading the tangram.min.js from Mapzen rather than a local copy and all is now good. How do you host Tangram locally?

**Comment by bcamper** [comment]
Hi! You've likely come across an issue that we need to address, which is that due to the manner in which Tangram loads its Web Workers, there are some restrictions on how it can be hosted/loaded.

For background, in order to load Web Workers, Tangram needs a URL to a full copy of itself. It currently does this by looking for the `<script>` tag that it was loaded from, but this means that:

- It must look for known/expected library names, currently a file named either `tangram.min.js` or `tangram.debug.js`.
- It must be able to load Tangram itself in isolation from other code, which means it currently cannot be bundled with other dependencies.

We are working to address this with a different bootstrapping approach. In the meantime, you should be able to host Tangram locally as long as you keep it as a separate file named either `tangram.min.js` or `tangram.debug.js`. Please let us know if that does not work!

I will open an issue for this general problem and link here in case you would like to follow.

**Comment by matbeard** [comment]
I see. I was bundling the tangram.min.js file with Leaflet and various other related scripts as part of my Laravel build process.

Separating out the Tangram script and loading it separately works fine. Thanks.

**Comment by bcamper** [comment]
Good to hear. Sorry for the current limitation, we definitely plan to address that.

**Comment by bcamper** [comment]
See #252 for more info and future solutions.
