### ISSUE TITLE
Label Direction

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#256]
I'm back to annoy you good people at Tangram.

I have been trying to get my labels to follow the direction of the roads but I have not had any success. I want the road label's text to follow the direction of the road and not be in a straight line, is it possible to do this in Tangram?

![screenshot from 2016-03-01 10 35 18](https://cloud.githubusercontent.com/assets/7081695/13418891/5f3847e6-df9b-11e5-9240-c92d5f501827.png)

**Comment by bcamper** [comment]
Hi! Unfortunately we don't yet support curved labels on lines, though we definitely will be adding this. We know it's an important component of a robust renderer so it's high on our priorities, but to be realistic we probably will not be done with it for at least a few months.

In the meantime, you may be able to finesse things a bit to get closer to what you want:

- The example in your screenshot above is quite long. While multi-line labels aren't as common for lines as they are for points (and by default are disabled for the former but enabled for the latter), you could enable line breaks with the `text_wrap` parameter, which takes a number of characters past which to break the line. Maybe something like `text_wrap: 15` or `18` could work for outlier long labels?
- There's an undocumented/unofficial style parameter for the `text` style, called `line_exceed`. It takes a percentage value that determines how far text labels are allowed to go past the end of the line. Higher values allow more labels that won't look as good, lower values allow fewer labels that will fit better. The default is `80%`, you could try `line_exceed: 50%` or other numbers to see if it helps. This is undocumented, but will cause no harm if it is deprecated in the future (which would likely be done when default behavior improved anyway).
- You could have some custom logic for splitting or reformatting long labels. The `text_source` parameter allows you to write a JS function that returns the label text to use. The following example truncates a label and adds an ellipsis, probably not something you'd actually want to do in practice, but shows you the possibilities. We use techniques like this for normalizing or selectively displaying labels for some highways in OSM data.
```
text_source: |
    function() { 
        if (feature.name && feature.name.length > 10) {
            return feature.name.slice(0, 10) + '…';
        }
    }
```

We realize none of these are the real solution, but perhaps they can help made do while we improve the underlying functionality. Let us know if you have further questions on this.

**Comment by hasan9206** [comment]
Thank you for getting back to me so fast! Really appreciate the help, I am looking forward to seeing Tangram evolve into something greater.

I'm not sure if can use MultiLine labels for roads, my labels already just barely fit the roads and they are only single lines!

The `line_exceed` parameter looks really promising and I'm sure it will help improve the overall readability of the map.

The ability to use functions in the text source is brilliant! I was thinking to trying to use something like this on the longer labels I have for the POIs and the roads, this will work perfectly for what I had in mind. I wanted to be able to truncate the labels that were too long and add ellipse towards the end, and display the full label when the pointer hovers over the label.
How can I display the full name on hover?

On another note, I have been able to get my other labels working pretty well, there is just some overlapping between the labels in different layers ( I have already assigned different priorities to them as required ). The labels are drawn according to the priority set but I want the lower priority label (the one with the higher Priority value) to not be drawn when there is a conflict.
![screenshot from 2016-03-02 10 21 35](https://cloud.githubusercontent.com/assets/7081695/13451464/140074da-e061-11e5-86b1-f14844a33716.png)

**Comment by nvkelso** [comment]
Thanks for the screenshot! Can you confirm which version of Tangram you are using? The latest is 0.5.x and includes better label collision logic.

**Comment by hasan9206** [comment]
I thought I was using the latest version but I just realised that I am using the version hosted on Mapzen, the one referenced in the [walkthrough](https://mapzen.com/documentation/tangram/walkthrough/) and it's version 0.4, I'll change the path of the source file to use the latest version I have locally.

**Comment by nvkelso** [comment]
Ooops! We'll fix the link in that demo.

An alternative to using your local Tangram build is to point to the hosted 0.5 file instead of 0.4 in the example src code.

**Comment by hasan9206** [comment]
I have been meaning to switch to my local Tangram build for a while now, I want to expand my map and include some functions after I sort out all the basic labelling and display issues (which I am almost done with, thanks to all the help I've gotten here!). 

Using my Local Tangram build has solved the collision issues I was facing, but now my POI icons disappear when the label text appears (not always but on most occasions)

**Comment by nvkelso** [comment]
Make sure to set an offset of the text from the icon to 50% or more of the icon sprite size. Also to set the priority of the icon to a lower number than the text, so the text wins in a collision. If you have multiple types of labels, you may want to set several different pairs of priorities to make the collisions more predictable. But the current version of Tangram they won't be 100% predictable because the icon and text parts of the label aren't yet integrated to act as one unit.

**Comment by hasan9206** [comment]
Shouldn't I make the icon win in a collision? Better to have the icon instead of the text in case of collision I think.

How would the pairs of priorities work? I have multiple types of labels in POIs and am not sure about how to resolve their conflicts.

**Comment by hasan9206** [comment]
I was going through the Tangram Documentation, specifically the Conceptual Overviews and I came across ["(You can’t currently rotate or tilt our cameras.)"](https://mapzen.com/documentation/tangram/Cameras-Overview/).

Does this mean you guys plan on adding the ability to rotate and tilt the cameras in the future?

**Comment by bcamper** [comment]
Yes, we plan to add tilt + rotate support eventually, and our native mobile implementation [Tangram ES](https://github.com/tangrams/tangram-es) already has this. For Tangram JS, we currently use Leaflet both as the predominant external API, and for basic input handling. Since Leaflet doesn't support anything besides a top-down view, we could not expose this from Tangram and keep the view coordinates consistent between the two systems. So it might require us to move away from Leaflet or at least provide a parallel API, which is a more significant effort. In the meantime, if you're curious, there are some experiments in our [Sandbox](https://github.com/tangrams/tangram-sandbox) where the view is tilted from within a shader, but note that this does break consistency between Tangram view coordinates and Leaflet coordinates (e.g. mouse clicks and view movements will not match between the two, making it more of a "view-only" mode).

**Comment by hasan9206** [comment]
Yes I did look through `Tangram ES` and was really impressed at how smooth the whole thing was on the mobile ( a couple of my colleagues are using `Tangram ES` to implement `Vector Tiles` on mobile ). 

I was looking through [osm buildings](http://osmbuildings.org/?lat=52.52141&lon=13.40895&zoom=16) and wanted to see if I could get a similar sort of feel through Tangram, the examples in the `Sandbox` look promising and I'll try to implement them and see how it goes. Since I am only really looking to view the map with a tilted camera breaking consistency between Tangram View coordinates and Leaflet coordinates is not an issue for me.

Moving away from Leaflet sounds like a very cumbersome thing to do I don't envy you that task. Thanks Again for taking the time to respond to my queries, I really appreciate it!

**Comment by bcamper** [comment]
Back to the previous question about icon and text offsets, while the better solution we're moving towards is to have a unified icon/text style, for now you can place text below an icon like this:

```
draw:
   icon:
      priority: 1 # icons have highest priority so they will always show
      sprite: ...
      size: [16px, 16px]
   text:
      priority: 2 # text will shown when it fits
      anchor: bottom # top-line of text is anchored to bottom of point
      offset: [0px, 8px] # additional offset down (half of icon height) so that text is below icon 
      font:
         ...
```

Both the `icon` and `text` styles are rendering against a point geometry in this case. So the icon is centered on the point (default of `anchor: center`), and the text label is anchored down (`anchor: bottom`), but still needs an additional `offset` in order to ensure the top of the text is below the icon (since the two are independent entities). In the future this will positioning be automatically calculated to simplify the style.

More examples (some pretty complex!) in our hosted styles like Cinnabar:
https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L3801-L3816

For tilting, the most straightforward example is here:
https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tilt.yaml

Closing this issue out but feel free to file future ones with specific questions. Best of luck and we'd love to see what you build!
