### ISSUE TITLE
Update docs for 0.6.0 + 0.6.1

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#276]
Relatively small public syntax footprint in the 0.6 releases:

https://github.com/tangrams/tangram/releases/tag/v0.6.0
https://github.com/tangrams/tangram/releases/tag/v0.6.1

**Comment by meetar** [comment]
Fixed with:

- add `url_params` https://github.com/tangrams/tangram-docs/commit/eb87d45ee6eff2fa2e4d07b5118608bc6287d55f
- update color parameters https://github.com/tangrams/tangram-docs/commit/d492f4ff04f54b075919254b12741392d1f562cb
- update point light defaults https://github.com/tangrams/tangram-docs/commit/f309547aa33caa67ae6cb5842a9e1b3bfa9c3ea5
