### ISSUE TITLE
Complicated OSM building doesn't draw at zoom 19

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#307]
The SF Ferry Building tower will draw at zoom 18, but fails at zoom 19. 

Is this related to building outlines not drawing in general? But why does part of the tower draw?

19/37.79545/-122.39364

z18:
<img width="470" alt="screen shot 2016-05-10 at 11 45 18" src="https://cloud.githubusercontent.com/assets/853051/15158441/d34bc636-16a4-11e6-85ff-59654916992c.png">

z19:
<img width="826" alt="screen shot 2016-05-10 at 11 45 11" src="https://cloud.githubusercontent.com/assets/853051/15158442/d361ec2c-16a4-11e6-844d-eae5b3e30559.png">

**Comment by nvkelso** [comment]
The building texture is rendering, but not the outlines?

**Comment by meetar** [comment]
I think your last guess is right – all building outlines seem to disappear
at z20:

http://tangrams.github.io/bubble-wrap/#20/37.79406/-122.39696

**Comment by bcamper** [comment]
I have to confirm but I think it is this issue: https://github.com/tangrams/tangram/issues/267

The lines are thin enough that they collapse at z20. This can be verified by increasing the outline width to see if they draw. We started seeing this frequently when we switched to z16 tile overzooming, since the data is being scaled up by many more factors now.

**Comment by bcamper** [comment]
I've confirmed my hypothesis and was able to hack together a quick fix, but would like to spend some more time thinking about the best way to address. Will update #267 and here.

**Comment by nvkelso** [comment]
I agree this is a dup, closing this in favor of #267.
