### ISSUE TITLE
Clamp line texture UVs in shader + create `texcoord` shader variable

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram#319]
We've discovered an issue with line UVs, where the hardware multi-sample antialiasing (MSAA) is causing the texture UV varying, which should be within a range of 0-1, to sometimes interpolate _outside_ of that range. When those UVs applied with a `fract` (used for repeating a line texture pattern such as a dash), values outside [0, 1) cause light and dark "fringes" at the edges of the line:

![tangram-tue may 31 2016 11-57-34 gmt-0400 edt](https://cloud.githubusercontent.com/assets/16733/15683192/181b2c1c-272f-11e6-959b-2b0509d420f2.png)

These can be isolated in the shader showing UVs outside [0, 1):

![tangram-tue may 31 2016 12-57-45 gmt-0400 edt](https://cloud.githubusercontent.com/assets/16733/15683239/4dc7d14e-272f-11e6-9b7f-5b68b90e36c2.png)

**Proposed Solution**
Fixing this appears to require clamping/adjusting the UVs in the shader. Currently, many custom Tangram styles access `v_texcoord` directly, while other attributes `position`, `color`, and `normal` are accessed through dedicated variables that allow for projection, line extrusion, and other pre-processing to be applied before user-defined shader code is run. We should do the same for texture UVs, creating a `texcoord` variable that includes any necessary UV adjustment. It may also be appropriate to create `texcoord` shader block to go along with this change, and clarify the time at which user UV adjustments should be made (TBD).

**Comment by bcamper** [comment]
Note: this was noticed during the re-write of the polyline builder to use element arrays (https://github.com/tangrams/tangram/pull/313), however the issue appears to already exist both on Tangram JS master, and in Tangram ES.

**Comment by bcamper** [comment]
cc @blair1618 @patriciogonzalezvivo @meetar @dmvaldman @karimnaaji

**Comment by dmvaldman** [comment]
The diagonal artifacts I was seeing (on the element-array JS side) turns out to be a bug caused by flipping the texture coordinates. Working on a fix now. Only the vertical artifacts at the line ends are visible now, and no diagonal ones.

**Comment by blair1618** [comment]
I am not 100% certain of how this is happening, but it seems that the anti-aliasing technique used by the GL driver here is sampling points that fall slightly *outside* of these triangles when it composites the final pixel color. Using barycentric interpolation, the texture coordinate varyings may then fall outside the [0, 1] range of their respective attributes. This idea is supported by the fact that disabling multi-sampling or super-sampling will eliminate these artifacts in both engines. 

I'm not totally convinced by this hypothesis because multi-sampling or super-sampling should also re-sample the depth buffer at the sample points and should therefore not execute the fragment shader on samples that fall outside the original triangle.
