### ISSUE TITLE
detect mixed spaces/tabs or missing parameters

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#338]
![capture](https://cloud.githubusercontent.com/assets/459970/16214894/e15f62e0-372a-11e6-968d-7664c623c01e.PNG)

In this case the normal map just silently failed to draw, but the rest of the map did. Not sure how extensive the current internal linting is or if there's any kind of error which could be thrown in this case...

**Comment by louh** [comment]
[Tabs are technically forbidden in YAML](http://yaml.org/spec/1.2/spec.html#id2777534), and Tangram's internal YAML parser has not resolved this since the issue was opened in 2013, even after the YAML spec creator weighed in: https://github.com/nodeca/js-yaml/issues/80

The summary is that we have to catch these errors ourselves or do the work of patching js-yaml upstream.

Incidentally, I have considered writing functionality in Tangram Play that can highlight these as errors, or convert them for you. We already insert spaces instead of a tab character when you press tab, so there's no chance of accidentally inserting tabs when authoring in Play.

**Comment by meetar** [comment]
Illuminating: https://github.com/nodeca/js-yaml/issues/80#issuecomment-158592334 – would it be worth considering libyaml at this point?

**Comment by louh** [comment]
Libyaml is python, I believe...? Is there a direct JS port?

**Comment by meetar** [comment]
Ah, missed that. Not to my knowledge.

**Comment by blair1618** [comment]
LibYAML is a C library, with bindings to many languages. It could probably be transpiled to JS with emscripten but I'm not aware that this has been done already. LibYAML also has a SAX-style parsing interface, which deterred us from using it in tangram-es.

**Comment by bcamper** [comment]
From the research I've done, I believe js-yaml is far and away the best JS YAML library.

**Comment by louh** [comment]
Let's patch it!![](https://link.nylas.com/open/c3ccrw0t3xj00dylcqc5uc6ma
/local-
0c7eff53-ac75?r=cmVwbHkrMDAyNmY1YjRjYmNmNjQ2OTIxNmZhZjkzNzA0ZmU0OTdjODUxNGU4M2U3YzQ3Y2JiOTJjZjAwMDAwMDAxMTM4MTFiZDk5MmExNjljZTA5OWRhZmYyQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 21 2016, at 11:14 am, Brett Camper &lt;notifications@github.com&gt;
wrote:  

> From the research I've done, I believe js-yaml is far and away the best JS
YAML library.

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on
GitHub](https://github.com/tangrams/tangram/issues/338#issuecomment-227472337&r=cmVwbHkrMDAyNmY1YjRjYmNmNjQ2OTIxNmZhZjkzNzA0ZmU0OTdjODUxNGU4M2U3YzQ3Y2JiOTJjZjAwMDAwMDAxMTM4MTFiZDk5MmExNjljZTA5OWRhZmYyQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/ACb1tGUIgxWYXD4lcTmYhZBUp28_WTxPks5qN__ZgaJpZM4I6Rd3&r=cmVwbHkrMDAyNmY1YjRjYmNmNjQ2OTIxNmZhZjkzNzA0ZmU0OTdjODUxNGU4M2U3YzQ3Y2JiOTJjZjAwMDAwMDAxMTM4MTFiZDk5MmExNjljZTA5OWRhZmYyQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/ACb1tFSniRKmqkpS18DqrXeAhoyMhzP8ks5qN__ZgaJpZM4I6Rd3.gif)

**Comment by meetar** [comment]
Closing with WONTFIX as out of scope.
