### ISSUE TITLE
Tangrams used in  ie,  has SecurityError

### ISSUE THREAD

**Issue by ligai322** [tangrams/tangram#341]
tangrams used in  ie  brower , the error like

Tangram v0.8.0 [error]: Scene.load() failed to load  /style/scene.yaml: SecurityError SecurityError.

how can i sove it

**Comment by meetar** [comment]
Hello, can you please give us your operating system and version, as well as your IE version? And what kind of scene are you loading? Is it hosted publicly or locally?

**Comment by ligai322** [comment]
My operating system is  windows 8.1 , and IE is 11. 
Publicly and  locally  both has this problem. 
The publicly sample url is  https://tangrams.github.io/simple-demo/   ,and error info like this 
Tangram v0.4.6: Scene.load() failed to load scene.yaml: SecurityError SecurityError.
My locally sample use git code demo,do not change anything, publish in tomcat. has the same error like publicly sample.

**Comment by meetar** [comment]
Hello, we don't have Windows 8 available for testing here, but I've tested
it successfully in IE 11 on Windows 10... I've updated this demo to use the
latest version of the library, do you still get the same error?

**Comment by ligai322** [comment]
I have tested it successfully in IE Edge on Windows 10,  and  IE mode changed to IE 11 also successfully.
but it has error  when i tested it  in IE11 on Windows 8 or on Windows 7.

**Comment by ligai322** [comment]
This error is thrown when worker is created. 
![qq 20160627112019](https://cloud.githubusercontent.com/assets/3262486/16367756/357835ea-3c59-11e6-83ca-8cba674a708a.jpg)


The problem has been discussed in [stackoverflow website](http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string)，but I didn't find a solution.

**Comment by meetar** [comment]
Thanks for tracking that down! We'll review this and consider our options,
and post updates here.

**Comment by ligai322** [comment]
Thank you

**Comment by bcamper** [comment]
Hi @ligai322 - could you see if you can find a more specific IE11 build or sub-version number? We have tested this successfully with the current Tangram build in IE11 in Windows 10, and I know it used to work with an earlier Tangram build on Windows 8 (but I upgraded that machine to Windows 10! :)  This article also mentions that this bug was fixed in IE11 (it's dated after the Stack Overflow answer, so perhaps it's fixed in a version newer than what you have in your Win8 install?).

**Comment by blair1618** [comment]
I've just tested the current version of tangram on a laptop running Windows 8.1 Professional using Internet Explorer 11 (version 11.0.9600.18321). All of the demos behaved as expected and the browser console showed no security errors.

**Comment by ligai322** [comment]
Hi,  @blair1618,@bcamper 
Tangram is well done on Internet Explorer 11 (version 11.0.9600.18314)，but it has error using  Internet Explorer 11 (version 11.0.9600.16384).  

Whether Tangram could run on ie10 or not?  Do you have some document describes the tangram operating environment？

**Comment by bcamper** [comment]
Hi @ligai322, that version of IE11 was a preview (see [here](https://en.wikipedia.org/wiki/Internet_Explorer_11)). We believe this issue was fixed in the official IE11 releases.

**Comment by bcamper** [comment]
To your other question: Tangram **cannot** run on IE10, because IE11 was the first version of IE to support WebGL, which is used for all of Tangram's rendering. In general, Tangram should run on recent browser with WebGL support, and we regularly test on the current versions of Chrome, Firefox, Safari, and IE on desktop, as well as iOS Safari and Chrome Android.
