### ISSUE TITLE
allow lowercase data source types

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#352]
Currently `GeoJSON` etc are case-sensitive – can we make them case-insensitive?

**Comment by blair1618** [comment]
Every other string value used in the scene file is case-sensitive as well, if memory serves, so it seems inconsistent to me to make this one field case-insensitive. 

It's not often a problem with other values because they are all lowercase. In theory we could reduce the likelihood of errors here by making the accepted format strings lowercase, but that would break backwards compatibility :\

**Comment by dmvaldman** [comment]
We could convert everything to lowercase internally. That would make everything case insensitive, and backwards compatible, but it wouldn't allow the distinguishing between case in a scene file (don't think that is ever used?)

**Comment by bcamper** [comment]
I would prefer to keep these kinds of "enum" values case-sensitive to reduce ambiguity.

But we can improve these types of situations with better error messaging.

**Comment by bcamper** [comment]
**If** we wanted to accept other variants like `geojson` here (which I am not yet convinced of), I would prefer to do it by registering other data source types that are just aliases (e.g. we do/did this for the deprecated source types like `GeoJSONTiles`, which just point to `GeoJSON`), rather than blanket case conversion.

**Comment by meetar** [comment]
+1 to aliases and/or better error messages – and fwiw I've never had a problem with case ambiguity, but I very often have trouble with source type case sensitivity. ¯\\\_(ツ)\_/¯

**Comment by bcamper** [comment]
It is also something Play can help with through better auto-suggestion.

**Comment by blair1618** [comment]
Going fully case-insensitive would lead to a host of tricky problems. Does jsyaml compare keys with case sensitivity? Does it accept "True", "TRUE", "False", and "FALSE" as Boolean values? Would filter strings still be able to specify values differentiated by case? Would case be ignored in JS strings or GLSL strings? Etc.

**Comment by bcamper** [comment]
Yes, for all those reasons I think good intentions would cascade into further confusion :)

**Comment by irealva** [comment]
are there other values within tangram that must be capitalized to be valid?

**Comment by bcamper** [comment]
The cases I can think of are essentially "proper names":

- Adhering to "official" names, like [GeoJSON](http://geojson.org/), [TopoJSON](https://github.com/mbostock/topojson), etc. Those are the names of those formats, which is why they're capitalized that way. 
- Font family names are (I think?) case sensitive, but this might be platform-dependent, e.g. I think mixed case will work on some platforms (e.g. the web), but may not on ES platforms where we have to resolve font families to file names (@tallytalwar?). So we should be documenting/encouraging people to use capitalization according to the font face's "official" name, e.g. "Open Sans".

In all other cases that I'm thinking of, where Tangram introduced new terminology, it's **all lower case**, e.g. `lighting: directional`, `style: polygons`, etc.
