### ISSUE TITLE
feature properties dropped at low zooms?

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#364]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- open https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fff18ab511db27b17db1b07795fe56790%2Fraw%2F1f03f6e952af0bdbdcc3a006ee464354a91bb441%2Fscene.yaml#2.216496022133511/37.09/-84.75

**RESULT:**

<img width="469" alt="screen shot 2016-07-25 at 11 21 27 am" src="https://cloud.githubusercontent.com/assets/459970/17106617/fe349594-5259-11e6-8be6-22b4c338cbda.png">

**EXPECTED RESULT:**

<img width="437" alt="screen shot 2016-07-25 at 11 22 11 am" src="https://cloud.githubusercontent.com/assets/459970/17106632/119b2eea-525a-11e6-92f3-192755663874.png">

To get this, you have to do an explicit check for the `languages` property:

```        filter: |
            function() { return feature.languages && feature.languages.indexOf('es') !== -1 }```

Oddly, this property exists everywhere at higher zooms – as though at lower zooms, the feature is dropped from features under a given area.

**Comment by irealva** [comment]
Yep, this happened for a tutorial file I was working on. It's here: 
https://github.com/tangrams/tangram-tutorial/blob/415561a32cb66f0f552b4e210b23abc29aa7773a/src/Assets/tutorial-files/filters3.yaml

**Comment by bcamper** [comment]
Non-tiled data sources are tiled on the client with the `geojson-vt` library. This will drop entire features at some zooms when they are too small to appear. It will never drop feature *properties* (as far as I know/have seen), but the features themselves may be culled.

In this case, it looks like several of the features in the data source file don't have the `languages` property, such as:
```
Object {name: "Guinea Bissau"}
Object {name: "Somaliland"}
Object {name: "West Bank"}
```

Whenever such features are in view, you're getting an error because you're trying to access non-existent properties, so you need to check for their existence, as mentioned: `function() { return feature.languages && feature.languages.indexOf('es') !== -1 }`.

**Comment by dmvaldman** [comment]
Would it make sense to put user-defined scene file functions in try/catch blocks? We could then show an error in Tangram Play

**Comment by bcamper** [comment]
@dmvaldman yes that makes sense. We do that in the [`parseFeature()`](https://github.com/tangrams/tangram/blob/master/src/styles/style.js#L197) method, where most user-defined functions are called (for `draw` properties like `color`, `order`, etc.), but it looks like we do not for `filter` functions.

The place to add this for `filter` would probably be in this call to [`layer.filter(context)`](https://github.com/tangrams/tangram/blob/master/src/styles/layer.js#L407-L408).

Would you like to add it? :)

**Comment by meetar** [comment]
> Whenever such features are in view, you're getting an error because
you're trying to access non-existent properties

Makes sense, but in that case why does the map render properly one zoom
level higher?
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fff18ab511db27b17db1b07795fe56790%2Fraw%2F1f03f6e952af0bdbdcc3a006ee464354a91bb441%2Fscene.yaml#3/29.54/-82.09

I'd assume if the features were missing the property, and were missing it
at all zooms, the filter would fail at all zooms.

**Comment by bcamper** [comment]
The feature itself only appears at certain zooms, so at some zooms, that
error condition (missing property) is never expected. I couldn't find any
instances in testing where a specific feature was present across zooms, but
with different properties -- if you do, let me know.

On Wed, Jul 27, 2016 at 10:43 AM, Peter Richardson <notifications@github.com

**Comment by meetar** [comment]
Threw a log() in the filter function to see which feature was causing the trouble: turned out to be Guinea-Bissau, on the west coast of Africa, which was just peeking into the tile, which explains why it only failed at low zooms.

**Comment by bcamper** [comment]
Yep I found many others like it (that had no properties for whatever
reason).

**Comment by dmvaldman** [comment]
Reopening because I intend to put a try/catch statement to log such errors. I'll close when that's up.

**Comment by dmvaldman** [comment]
@bcamper what do you think of putting the try/catch statement [here](https://github.com/tangrams/tangram/blob/master/src/styles/style_parser.js#L23)

Also, I think this string wrapping + eval could be improved by using the `Function` constructor instead. We _could_ have the YAML value only be the body of the function (which is what the `Function` constructor accepts), or we could regex for the body (also tricky), or just wrap the user-inputted function in a new function that executes the user-inputed function.

**Comment by bcamper** [comment]
We may want to put the try/catch outside in the calling function, since we already have a try/catch for `parseFeature`, which also calls these (probably not great to have it in there twice?). We could remove that one instead, but I think it may catch other errors outside the functions. I would need to look closer to refresh my memory though, I can see the advantage of putting it deeper in.

Agree on converting to `Function`, I've looked at that a couple times briefly but not carried it through (there's always been some little gotcha). We would need to continue having the full `function() { ... }` in the YAML, for backwards compatibility (not really worth breaking all existing styles IMO). I also think it adds some clarity by explicitly identifying it as a JS function. (Besides all that, it's also the pattern we use to identify functions from other values! :)

**Comment by dmvaldman** [comment]
Yeah I wouldn't want 2 try/catches, I meant to also suggest removing the try/catch in `parseFeature`. 

The other suggestions (regex for the body of the function, or wrap the function) were to preserve backwards compatibility. Actually, not even to create any new forwards compatibility either ;-)

**Comment by bcamper** [comment]
Yep, makes sense to change the regex to pull out the function body.

**Comment by bcamper** [comment]
@dmvaldman moved these to use `Function` in https://github.com/tangrams/tangram/commit/4e9b0f1359b9f41b7fd9c1e60eb06d840e51aa1b
