### ISSUE TITLE
custom draw group names exhibit inconsistent order behavior

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#368]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- open https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F3357ad94337126f25e4142eace7de740%2Fraw%2Fc09ca185bdf1cc4f6bcedb6523e38aad58ae8c5a%2Fscene.yaml#16/40.6998/-73.9891
- comment out lines 19-20:
```
_highwayStyle:
    style: lines
```
- uncomment line 21:

`# lines:`

**RESULT:**

The order changes, and the _highwayStyle layer is drawn on top of the other roads instead of beneath them.

**EXPECTED RESULT:**

The ordering will be the same as before.

(99% certain this is a syntax misunderstanding and not a bug)

**Comment by bcamper** [comment]
When the `_highwayStyle` `draw` group is present, you are drawing the lines *twice*: once for the inherited `lines` group, and once for `_highwayStyle`.

`_highwayStyle` is given `order: 0` so you see the red lines underneath with gray lines on top (`lines` at `order: 1`).

When you comment out `_highwayStyle`, the lines are only rendering once, for `lines`. They are still in fact rendered underneath (you can see other gray lines over them). You don't see the second set of gray lines overlaid on them, because they are only being drawn once, and their color and width are being overridden by `_highwaySubLayer`.

Every unique `draw` group name will cause the geometry in that layer to be drawn another time. This is also why I think it is generally not a good idea to use custom draw group names like `_highwayStyle` unless you really intend to draw the same geometry multiple times -- if you use the default style names, it's harder to do this unintentionally (you can only have one `lines` key).

**Comment by meetar** [comment]
:+1: Thanks!
