### ISSUE TITLE
`stroke` width of 0px is still visible

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#369]
A `stroke` width of `0px` is still visible:

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F7a0369ca75be0c1130129803c6fad011%2Fraw%2F991eea2b714bf274422faaf733d2b6f0f051c891%2Fscene.yaml#5.22311994892621/40.661/-73.907

**Comment by dmvaldman** [comment]
I noticed this as well. Turns out that setting `lineWidth = 0` is ignored by a canvas context. 

From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth), "Zero, negative, Infinity and NaN values are ignored."

This means the `lineWidth` will be drawn with whatever the previous value was. We should check for a 0 value and not call a stroke command.

**Comment by bcamper** [comment]
Interesting!
