### ISSUE TITLE
Integer shader defines are not injected correctly

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram#376]
For bug reports, please use this template:

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Go to [Tangram Play](https://mapzen.com/tangram/play) and open the 'default' example scene
- In `styles.buildings`, replace the value of the `shaders` key with:
```yaml
defines:
    COMPONENT: 2
blocks:
    color: |
        color.rgb *= vec3(min((worldPosition()[COMPONENT]*.001 + .5),1.));
```
_or_
 - Open the gist saved here: https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2F33930de35eb15bfde8573f2574a3e2cf%2Fraw%2F4d6646d671a72cd0c0700f08b9797b9f6e6ca2ce%2Fscene.yaml#17.8440/40.71654/-74.00552

**RESULT:**

The shader fails with a compilation error: `ERROR: 0:535: '[]' : integer expression required`

**EXPECTED RESULT:**

I expected the shader to interpret `COMPONENT` as an integer (using the GLSL ES grammar) and compile successfully. 

**ENVIRONMENT:**

Mac OS 10.11.6, Firefox 48

**OTHER:**

Also strange is the fact that if I use quotes for the define, i.e. `COMPONENT: '2'` the value is correctly interpreted as an integer. 

Since the C/GLSL preprocessor is strictly a text replacement system, I would expect for `defines` to do just that. 

The sample provided in the documentation pages also indicates that integer values should remain integers: https://mapzen.com/documentation/tangram/shaders/#defines

**Comment by bcamper** [comment]
This was an intentional design decision a long time ago, meant to ease the learning curve on `#defines` and avoid gotchas with GLSL floats, but:

- Given that Tangram ES doesn't implement this behavior, there doesn't seem to be any real-world conflicts in current styles (we should test against sandbox/blocks before releasing a change though).
- I agree it's reasonable to treat our `defines` values as a straight string passthrough since it's how the underlying preprocessor works.
- People have to deal with GLSL anyway so I can see this being more confusing than not. The one caveat here is that for people configuring an existing style, such as a block, this will not be obvious (the need to put a `.` float qualifier when overriding or setting a specific `define`).

@patriciogonzalezvivo what are your thoughts here?

**Comment by bcamper** [comment]
To clarify, part of the original reasoning here was that 99% of the time, the number value you want in GLSL is a float. (Values for things like loop iterations are valid but rare.)

**Comment by bcamper** [comment]
As far as the quoting behavior, whether we decide it's desirable, I think it's explainable (to me it's probably equally obscure as GLSL's native operation, but at least that's a standard):

- All YAML numbers are coerced to floats.
- All YAML strings are passed through as-is.

**Comment by bcamper** [comment]
Alright, I attempted to update JS to match ES behavior, but I've run into a blocker:

Because JavaScript only has a single "number" type for both integers and floating point, there is no way to disambiguate between YAML values like `value: 1.0` and `value: 1`. Both are parsed as the JS number value `1`, and native JS function `parseFloat('1.0')` similarly returns `1`.

I went down a rabbit hole trying to think of a way around this. The only plausible idea I had (which is pretty heavy-handed anyway) was to have js-yaml (we already run a fork to remove write-support) add context indicating the original source number was floating point (i.e. included a decimal point), either with `Object.defineProprety`, or with ES6's ability to subclass the built-in `Number` type. But either of these require the value to be an object instance and not a number primitive (`Number` is a wrapper of the underlying number primitive type). This causes problems with stringifying/cloning (when copying between threads, merging objects, etc.).

It's possible there are ways around this, but it would probably introduce a lot of special handling and/or gotchas that would likely be pretty brittle.

**Comment by blair1618** [comment]
Ok I think I see. So if you had a `define` written as `value: 1.0` the number would be parsed into a JS 'Number' and then when you string-ify it to inject into the shader the result would be 
```
#define value 1
```
Is that the issue?

Is there any way to access the original string from which the value was created?

**Comment by bcamper** [comment]
Yes that's exactly the problem, and no, without major changes to a js-yaml fork, it is not possible to retrieve the original string value.

I'm not sure exactly how to interpret the spec, but I don't think the behavior is "wrong" per se: js-yaml does properly parse integers and floating point numbers, but the language itself makes no distinction, so the native data values resulting from parsing are indistinguishable.

**Comment by bcamper** [comment]
So I'm returning to this summary of the current JS logic, which I don't think is too difficult to explain :)

- All YAML numbers are coerced to floats.
- All YAML strings are passed through as-is.

**Comment by meetar** [comment]
+1 for "explicable"

**Comment by blair1618** [comment]
js-yaml _is_ a little bit "wrong" here because integers and floats are distinct types in the core schema: http://www.yaml.org/spec/1.2/spec.html#id2804923

This means, for example, that js-yaml can't correctly parse documents that are valid by the YAML 1.2 spec, like this:
```
--- 
values: 
  1: "integer one"
  1.0: "floating point one"
```
(This document is parsed correctly by yaml-cpp, http://www.yamllint.com/, http://codebeautify.org/yaml-validator, etc.)

Regrettably, for the specific case of our `defines` the only practical solution I can see is to work around this behavior by requiring integers to be quoted, as is currently the case on tangram-js. We'll need to update tangram-es with this work-around to ensure consistent behavior.

**Comment by hjanetzek** [comment]
Another workaround would be to suggest writing ```INTEGER_ONE: int(1)``` :)

**Comment by bcamper** [comment]
I am closing this one for now since we don't seem to have any feasible way around it on the JS side. Can revisit if one arises :)
