### ISSUE TITLE
Is it possible to modify feature properties on the client?

### ISSUE THREAD

**Issue by aratcliffe** [tangrams/tangram#381]
I have an app that's currently using Leaflet.MapboxVectorTile for vector tile rendering. It uses data-based styling and allows the user to modify some of the feature properties on the client. Is it possible to do this using tangram?

**Comment by bcamper** [comment]
Hi @aratcliffe - could you describe a bit more about the mechanics of your app? That may help us recommend the best approach. For data loaded from vector tiles, you cannot directly modify the feature data after loading (this is partially because the data is loaded from a separate Web Worker thread... though it might be possible in the future to have an API that proxies changes to those features from the main thread to the appropriate worker).

However, Tangram offers other facilities that may support your use case. For example, it may be possible for you to store the additional or modified properties in a separate object and then reference that (along with the original feature data) in your styling rules (in the Tangram scene file). Happy to suggest how this might work if we have more ideas of what you want to accomplish.

**Comment by aratcliffe** [comment]
Hi @bcamper, the app loads statistical information for a road network. This includes static information about each road segment, the road name, it's distance in metres, the speed limit etc. and invariant statistical information about the time period the data represents. On the client the user can perform further analysis on the data, for example dragging a slider to determine what percentage of vehicles traversing a segment travelled at greater than the selected speed. These analyses update calculated fields in the feature data. In addition the styling rules themselves can change in response to some analyses. The current implementation therefore updates both the feature data and the rules used to style it.

**Comment by bcamper** [comment]
Sorry for the delay. Hmm, the best way to do that in Tangram would probably be to maintain a "sibling" data structure that allows you to join your tiled features with any new run-time calculations. You could provide this object in the [`extra_data`](https://mapzen.com/documentation/tangram/sources/#extra_data) field of the data source, and use it to update the tiled data in conjunction with the data source [`transform`](https://mapzen.com/documentation/tangram/sources/#transform) method -- the latter allows you to write a JS function to modify the tiled data (one time, not continuously), with access to the `extra_data` object.

As you complete new calculations at run-time, you could trigger a re-evaluation of the tiles (e.g. refresh of the `extra_data` re-running of the `transform` function) by calling the `Scene.updateConfig()` method.

So the flow would be something like this:

- Tiles load and draw with initial data
- User interacts (either directly with features or other UI)
- Resulting data from user interactions (at least that data needed to update tile features) is stored in a JS object set as the data source's `extra_data` parameter
- Code to apply user interactions to tile data is a JS function provided as the data source's `transform` parameter
- `Scene.updateConfig()` is called whenever new interactions are complete / new data is available.

If you're interested in giving this a further try, please let me know and I'm happy to look at any WIP implementation.

**Comment by aratcliffe** [comment]
Hi Brett, thanks for the detailed reply. I'll have a look at applying this to our app when I'm back at work next week.

**Comment by bcamper** [comment]
Closing, feel free to open a new issue with specific questions.
