### ISSUE TITLE
`anchor: center` interferes with point priority assignment

### ISSUE THREAD

**Issue by meetar** [tangrams/tangram#391]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- open https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F3a77f8b02276e146a223765e9fc4b991&lines=32#9.8600/39.9303/-75.3498
- uncomment line 32 (highlighted): `anchor: center`

**RESULT:**

The label for "Philadelphia" is replaced by the label for "Camden", which has a lower priority.

**EXPECTED RESULT:**

The text label should have moved to the center of the point, and remained visible.

If `collide: false` is specified on Philadelphia's layer, the label remains visible, as expected.

**Comment by bcamper** [comment]
The problem is not actually related to `priority`, but to tile boundaries. The "Philadelphia" label will not fit with a `anchor: center` because of tile boundaries. You can comment out the other labels (for "Camden") entirely and see that they are unrelated to the "Philadelphia" behavior.

![screen shot 2016-08-22 at 4 29 46 pm](https://cloud.githubusercontent.com/assets/16733/17870488/bfec9c9a-6885-11e6-83e7-504844dedf96.png)
