### ISSUE TITLE
Serving vector tiles with geojson-vt

### ISSUE THREAD

**Issue by Strainy** [tangrams/tangram#413]
Hi everyone,

First of all, I'd just like to thank all the contributors to Tangram for doing such an awesome job. This library is great and so far I've really enjoyed using it!

I'm successfully using Tangram within a WebView component in a React Native application. However, I've run into a use case where I need to store vector map data for a certain area offline and (where the user does not have an internet connection) render the map with this data.

I can reference a raw GeoJSON file in my scene file, and that works fine. However, the files will generally be quite large (60-70MB) and there's some stuttering when panning and zooming.

MapBox have a nifty solution for taking a large GeoJSON file and slicing it into vector tiles "on the fly" within the browser called [geojson-vt](https://github.com/mapbox/geojson-vt). You can request tiles like so:

```javascript
// build an initial index of tiles
var tileIndex = geojsonvt(geoJSON);

// request a particular tile
var features = tileIndex.getTile(z, x, y).features;
```
Is there any way to combine this functionality with Tangram?

Thanks again!

Strainy

**Comment by bcamper** [comment]
Hi @Strainy - we actually use geojson-vt under the hood to tile raw GeoJSON files like yours on the fly (the same way Mapbox does). You're right that there's a significant hit to load and tile those at run-time. For our native renderer, [Tangram ES](https://github.com/tangrams/tangram-es), we are working on adding on-device caching (which could for instance apply geojson-vt once and save the results for future use), but this is trickier for web environments where there is typically not a lot of local storage available in-browser (I'm not sure how this works in React Native).

Since geojson-vt can run in node.js, what I suggest is to write a one-off node script that tiles your data and saves them to individual GeoJSON tile files, then just point Tangram at those files with a local tile template like `url: path/to/tiles/{z}/{x}/{y}.json`. Longer term we'd consider providing a script with Tangram to help people do this, but for now you'd have to do it yourself. You could also combine this with the new `bounds` parameter for data sources in Tangram JS [v0.10.0](https://github.com/tangrams/tangram/releases/tag/v0.10.0).

Hope this helps, let us know if not clear. Glad you are enjoying Tangram!

**Comment by Strainy** [comment]
Hi @bcamper, thanks for the prompt response. 
WebViews in Android have issues calling locally stored tiles as it has to use the "file://" protocol. It's not really feasible for react native to function as a web server for the WebView either. 

Essentially, how it works is there's a simple bridge between react and the WebView control where data can be sent and received on both ends. Is it possible to provide a function instead of a Uri in the scene file as a source? That way I could request a tile straight over the bridge! 

I did notice that there's a "transform" function. Perhaps I could manipulate the "extra_data" parameter to provide data from the bridge as tiles are requested. I'll give this a try.

Be great if you had any other ideas. I'd be open to working on a PR to add function data sources if that's the only avenue you can see.

Thanks again!

**Comment by Strainy** [comment]
Hey @bcamper - thanks for your assistance on this. For my purposes, it would be ideal if I could extend the XMLHttpRequest prototype to redirect requests for tiles to the WebView bridge. 

Unfortunately, changes I make to the XMLHttpRequest prototype don't seem to be adopted by the Tangram library. Here's my attempt if you'd like to have a quick look: https://plnkr.co/edit/HvmwrqpyLg27sIoHhnic?p=preview 

You'll notice that the request for the scene file shows up in the console. But none of the tile requests made by Tangram are logged.

Off the top of your head, is there any particular reason why this would occur? Looking at the source, it doesn't seem like Tangram is doing anything particularly odd with XMLHttpRequest that would prevent it from adhering to the new prototype functions.

Thanks very much :)

Strainy

**Comment by bcamper** [comment]
Hi @Strainy, the idea to monkey-patch XMLHttpRequest as an interim step
makes sense, but the reason you're not seeing it work is that Tangram makes
these requests on its *worker threads* (not on the main thread where you're
modifying it). This is kind of hacking the original intent, but if you want
to try it, you could possibly use the data source [`scripts`](
https://mapzen.com/documentation/tangram/sources/#scripts) parameter to run
your XMLHttpRequest modifications -- any files listed in `scripts` *will*
be executed on the worker threads (the whole purpose of the parameter is to
allow people to bring other scripts into scope for use in the worker, since
the regular main thread scope isn't available). I haven't tried this
specifically but as far as I know it should work.

More broadly, I think your idea of a "direct" function-based data source
makes sense, and I'd be interested in implementing it -- but I can't offer
a precise timeline for that yet, so in the meantime I suggest you try the
above and let us know how it goes?

Brett

**Comment by bcamper** [comment]
@Strainy strangely, I'm receiving your comments via github email, but they are not showing up on the page here?!

**Comment by bcamper** [comment]
@Strainy I've added issue #421 for the idea of dynamic JS-function data sources.

**Comment by Lovebubu** [comment]
> Hi everyone,
> 
> First of all, I'd just like to thank all the contributors to Tangram for doing such an awesome job. This library is great and so far I've really enjoyed using it!
> 
> I'm successfully using Tangram within a WebView component in a React Native application. However, I've run into a use case where I need to store vector map data for a certain area offline and (where the user does not have an internet connection) render the map with this data.
> 
> I can reference a raw GeoJSON file in my scene file, and that works fine. However, the files will generally be quite large (60-70MB) and there's some stuttering when panning and zooming.
> 
> MapBox have a nifty solution for taking a large GeoJSON file and slicing it into vector tiles "on the fly" within the browser called [geojson-vt](https://github.com/mapbox/geojson-vt). You can request tiles like so:
> 
> ```js
> // build an initial index of tiles
> var tileIndex = geojsonvt(geoJSON);
> 
> // request a particular tile
> var features = tileIndex.getTile(z, x, y).features;
> ```
> 
> Is there any way to combine this functionality with Tangram?
> 
> Thanks again!
> 
> Strainy

Hi Strainy,

I am facing a similar task. I have to render the geojson data on the leaflet. How could I add my geosjon data to the Tangram? Could you give a example? Do I need to change the code in scene.yml? Thank you!

**Comment by bcamper** [comment]
Hi @Lovebubu --
You can load GeoJSON in Tangram simply by specifying it as a source in your scene YAML, e.g.:

```
sources:
    geojsonSource:
        type: GeoJSON
        url: path/to/data.geojson
```

See https://tangrams.readthedocs.io/en/latest/Syntax-Reference/sources/.
