### ISSUE TITLE
Specify texture resolution (1x, 2x) so sprite sizing is automatic

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#438]
For Mapzen house styles we specify sprites via [`x, y, width, height]` positions in the spritesheet image resource in the `texture` block in Tangram scene files. 

We create retina `@2x` assets, but Tangram still lives in a `@1x` world and we jump thru a lot of hoops in the `pois` section to specify a general `size` (that applied to the vast majority of icons) and override sizes for specific pois that are different than the general size. If we had provided a `@1x` spritesheet Tangram would mostly "just work". 

That has been a large amount of book keeping and largely a sunk cost, but as we iterate on new highway shields it turns out MOST are not the same size and we're spending a lot of time copying values out of Illustrator into the scene file, and when the asset changes in Illustrator, recopying values. 

It would be lovely if Tangram could learn how to do `@2x` size math :)

**Comment by bcamper** [comment]
We can get back to adding multiple-resolution support for sprites, but I'm confused on where the issue is now. All `px` sizes in Tangram are in logical CSS pixels (e.g. 1x size) and will likely remain that way (but can choose a higher-resolution sprite if available). The best thing to do with the current logic is to make all sprites 2x, and specify their `size` values at 1x in the layers. This will show the desired result at 2x, and simply scale down at 1x (not ideal but not too bad). I thought this is what we're doing now though? If so, where is there any copying of values out of Illustrator and why is it different from other sprites? Since Tangram doesn't have any rule-switching based on pixel density, why aren't all values simply exported at 1x size from the Illustrator script?

**Comment by nvkelso** [comment]
I'd like to _not_ specify sprite `size` at all in the draw block. Instead it should automatically size per the texture's size. But the texture definition is in **pixels** (as if the `@2x` asset were `@1x`), when the size is in **CSS** `px`. 

Right now we need to refer to the texture size in pixels (which is a script export out of Illustrator) and divide that by 1/2 to set the draw block's sprite size in CSS px, and then remember which sprites **aren't** that standard size, and then manually set their sizes. Since we already set the default sizes in the texture definition, I'm looking for a way to reuse.

Then for scaling up and down the icons are not always square so end up having to manually multiple the texture width and height to get the size for each stop. It would be nice to specify a % scale factor.

**Comment by dmvaldman** [comment]
If I understand this correctly...If the sprite automatically sized per the texture's size, then either

1) the texture size is 2x resolution, and the user's monitor is retina = ✔️ good
2) the texture size is 1x resolution, and the user's monitor is non-retina = ✔️ good
3) the texture size is 2x resolution, and the user's monitor is non-retina = ✖️ bad, scaled
4) the texture size is 1x resolution, and the user's monitor is retina = ✖️bad, fuzzy

There is no way for Tangram to make all the outcomes good "automatically" without specifying the actual size of the sprite. 

As @bcamper said, we could have all textures at 2x resolution and then down sample for non-retina screens (though the size must still be specified in this case). This increases the payload of the sprites, but since they are small it isn't a significant cost.

**Comment by bcamper** [comment]
Old discussion here for context: https://github.com/tangrams/tangram/pull/234

Correct @dmvaldman, though in my view while this option is not *ideal*, it is also tolerable (though agree that explicit 1x sprites would be better):

> 3) the texture size is 2x resolution, and the user's monitor is non-retina = ✖️ bad, scaled

In today's world, 1x and 2x do not capture the full range of devices, so we need a generic solution that allows for N number of pixel density sprite definitions.

@nvkelso agree that sizing by sprite % is a good step, it will still require some zoom-specific styling, but hopefully a lot less (more generic). I also think this is a prerequisite for supporting multiple pixel density sprite definitions, because as I understand it the 1x and 2x sprites don't always have the same scale/shape (e.g. the 2x resolution sprites are not strictly 2x bigger than the 1x).

I'll create a separate issue for specifying sprite size by %.

**Comment by pnorman** [comment]
> In today's world, 1x and 2x do not capture the full range of devices, so we need a generic solution that allows for N number of pixel density sprite definitions.

Just a reminder that with something like paparazzi you might be rendering to an arbitrary resolution for print, and the scale factor can be >10 for those devices

**Comment by nvkelso** [comment]
@bcamper Is this issue a duplicate of https://github.com/tangrams/tangram/pull/234 or the request for automatic sprite sizing different enough to warrant keeping open?

We're on a tangent now, but generally I've found:

- `@1x` = raster pixel asset
- `@2x`, `@3x` and beyond are best as a `@2x` vector asset (like SVG) with pixel snapping done on device. But if they are raster pixel assets than yes, occasionally they will be a pixel, or two, or three different to get the sharpest images.

**Comment by bcamper** [comment]
I believe this is reasonably covered by the functionality added for v0.14 in #234.
