### ISSUE TITLE
How to get multiple features at pixel?

### ISSUE THREAD

**Issue by nicholas-l** [tangrams/tangram#439]
Is it possible to have a getFeaturesAt({x, y}) which returns multiple features at the location?

P.S. Great work!

**Comment by bcamper** [comment]
It is not possible currently to select multiple features at a single pixel location, due to the way in which selection is implemented: features are drawn to a separate off-screen buffer using special color values uniquely identify them. Therefore each pixel can only encode a single feature (the one "on top"). It would be a significant change in implementation to support multiple features, but could be considered if there was enough user demand.

Thanks!
