### ISSUE TITLE
Strange v0.10.5 tile load warning

### ISSUE THREAD

**Issue by rgillan** [tangrams/tangram#442]
Have updated to v0.10.5 and are using production 1.0 Mapzen vector tiles.  Have made all the required changes to our style.yaml.  When we load a base map (Sydney) we sometimes see missing tiles.  Further digging shows Tangram reporting some tile load errors:

Chrome Console:
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/14/15073/9832/14: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/14/15074/9832/14: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/13/7536/4915/13: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/13/7538/4916/13: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/14/15073/9832/14: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/14/15074/9832/14: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/13/7536/4915/13: undefined
tangram.min.js:19
Tangram v0.10.5 [warn]: tile load error(s) for mapzen/14/15068/9830/14: undefined

It appears that the URL has the zoom appended to the end (a second time) in error.  Seems to happen on different zoom levels as well.

**Comment by rgillan** [comment]
Sorry, forgot to mention we are using TopoJSON tiles

**Comment by rgillan** [comment]
Digging further, looks like it's just the message that's displaying the zoom twice.  Still these tiles are being shown as undefined and they are being retrieved correctly (Chrome inspection shows the TopoJSON file being retrieved).  I have cleared the browser cache and the problem persists.  Any help guidance much appreciated.  I'll try and dig into the TopoJSON and see if there's anything obvious.

**Comment by bcamper** [comment]
Hi, thank you for reporting your issue. Could you please:

- Try upgrading to v0.10.6 and confirm if the issue still persists? (It included a bug fix that affected similar errors, though I cannot tell yet if it is the same issue.)
- Try the tangram.debug.js build and send the console log with stacktrace, which will likely provide more detailed information on where the problem is?
- Send the precise lat/lng where you are seeing the problem so I can see if it can be replicated on other YAML styles. Also I could check yours directly if you are comfortable posting it (no worries if not).

Lastly, as a side note, it is expected that the "zoom" is listed twice in the tile id. That string is an internal tile identifier within Tangram, and the library has two zoom concepts: one for the zoom of the tile data itself, and another for the display zoom, which will differ in cases where a `max_zoom` is used (recommended at `max_zoom: 16` for Mapzen tiles!). Tangram will scale up the lower zoom tiles at higher zooms (but still builds higher zoom versions of them to account for per-zoom differences in styling).

**Comment by rgillan** [comment]
Thanks for the prompt reply.  Silly question, where would I find v0.10.6 as the dist folder only shows .5?  Will follow up with more info shortly.

Co-ords are Sydney (-33.858192, 151.215871)

**Comment by rgillan** [comment]
[scene.txt](https://github.com/tangrams/tangram/files/570388/scene.txt)

**Comment by bcamper** [comment]
Ah yes, some confusion because the v0.10.6 patch was made as a separate branch, I need to update master branch to reflect those changes:

- https://github.com/tangrams/tangram/releases/tag/v0.10.6
- https://mapzen.com/tangram/0.10/tangram.debug.js or tangram.min.js (newest 0.10.x builds)

**Comment by bcamper** [comment]
Thanks @rgillan - I'm currently not seeing any errors for those tiles and scene file on *either* 0.10.5 or 0.10.6. Can you let me know if you are seeing errors on either of these links:

0.10.5:
https://tangrams.github.io/tangram-frame/?lib=0.10.5&scene=https://crossorigin.me/https://github.com/tangrams/tangram/files/570388/scene.txt#14/-33.8579/151.1123

0.10.6:
https://tangrams.github.io/tangram-frame/?lib=0.10.6&scene=https://crossorigin.me/https://github.com/tangrams/tangram/files/570388/scene.txt#14/-33.8579/151.1123

**Comment by rgillan** [comment]
OK, so strange.  I see no errors for either of the above two links.  I'll see if I can grab the contents of the specific tiles and see if something's amiss.  I'll update as soon as I have had a look.  Thanks again for all your help.

**Comment by bcamper** [comment]
No worries. Feel free to re-open with info if you have more problems.

**Comment by rgillan** [comment]
Just in case anyone else has an issue, turned out to be a gzip encoding issue clobbering UTF-16, and so tangram was getting some junk in the name: fields (we have a node.js server in the path compressing/cacheing the returned tiles for increased over the air efficiency).  Thanks Brett for your help

**Comment by bcamper** [comment]
Good to know, thanks for the info! I wonder if that is something we can catch and prevent at the Tangram level.
