### ISSUE TITLE
Delay when first loading scene 

### ISSUE THREAD

**Issue by MonkeybrainsDan** [tangrams/tangram#443]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Add Tangram layer to Leaflet map

**RESULT:**

There is a delay when first loading the scene: tiles don't appear until they're all loaded then they're rendered at once.

**EXPECTED RESULT:**

Tangram used to render tiles as they came in, similar to other raster tile maps. Depending on the complexity of the tiles and scene, there is a noticeable lag between when the webpage finishes loading and the map is first visible.

**ENVIRONMENT:**

Any and all WebGL-capable browsers
 
**OTHER:**

This changed way back between v0.8.2 and v0.9.0 but seems to have gotten worse sometime between then and now.
Thought I should bring attention to the UX issue of being presented with a blank map for a few beats.

**Comment by bcamper** [comment]
Thanks @MonkeybrainsDan - this is actually an issue we just fixed this week in master: https://github.com/tangrams/tangram/commit/92e445574b421520142574d91df8281d18783f52

It is pending release for v0.11.0, which should be released possibly *today*, or if not, then early next week. I'll leave your issue open until the fix is released to production.

**Comment by bcamper** [comment]
Released in v0.11.0.
