### ISSUE TITLE
WebGL INVALID_OPERATION errors

### ISSUE THREAD

**Issue by migurski** [tangrams/tangram#463]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Visit https://mapzen.com/products/maps/bubble-wrap/#lat=35.6836&lng=139.7593&z=14 in Safari or Mobile Safari.

**RESULT:**

- No map is displayed
- Errors in console:
    
        [Warning] WebGL: INVALID_OPERATION: drawElements: attempt to access out of bounds arrays (tangram.min.js, line 10, x244)
        [Warning] WebGL: INVALID_OPERATION: drawElements: attempt to access out of bounds arrays (tangram.min.js, line 10, x12)
        [Warning] WebGL: too many errors, no more errors will be reported to the console for this context. (tangram.min.js, line 10)

**EXPECTED RESULT:**

- A map
- No errors in console

**ENVIRONMENT:**

Safari 9.1 on OS 10.11.4 and Mobile Safari on iOS 9.3.5.

**Comment by burritojustice** [comment]
in Mac OS X Safari version 9.1.1 (11601.6.17) I am getting a map, but nothing in iOS Safari

**Comment by bcamper** [comment]
Confirmed this is a regression in 0.11.1, looking into it :/

**Comment by bcamper** [comment]
I have identified an issue that fixes this for me on both Safari 9.1 and iOS 8.1.1 and 10.1.1 (I don't have a device with 9.x). However, I haven't seen those same WebGL errors on the console (just an empty map) which makes me a bit nervous, but the nature of the issue (invalid GL objects) makes it plausible that it could manifest itself differently depending on conditions. 

@migurski can you see if this link fixes it for you (note it can take several seconds to load via precog, but it should come through):
https://precog.mapzen.com/tangrams/tangram/no-detach-shader/

**Comment by migurski** [comment]
👍 I see a map on desktop Safari and mobile Safari at that link 👍

**Comment by bcamper** [comment]
This should be fixed in newly release v0.11.2 (currently expiring CDN so should be available in ~15 mins).

Background:
Prior to v0.11.1, we would call `gl.deleteShader` on each shader object, once a GL program was finished linking (`gl.linkProgram`); this is compatible across all browsers. Starting in v0.11.1, we reuse the individual GL shader objects across programs when possible (e.g. when the source code of the shader is identical), to remove unnecessary shader instantiation and compile time. To facilitate this, we switched to calling `gl.detachShader` after program linking. In contrast to actually *deleting* the shader, *detaching* the shader does not leave the program valid across all platforms. It works in Chrome/FF, but not in Safari. Some [discussion here](http://stackoverflow.com/questions/27237696/webgl-detach-and-delete-shaders-after-linking/27243239#27243239
) suggests the spec is ambiguous, and that detach-after-linking should be avoided.
