### ISSUE TITLE
Pinch zoom problem

### ISSUE THREAD

**Issue by wotgl** [tangrams/tangram#476]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Created a simple map with custom design (.yaml) and vector tiles
- Code here: https://jsfiddle.net/a5007q4c/

**RESULT:**

Pinch zoom bug: route lines move across the screen

**EXPECTED RESULT:**

No bug :)

**ENVIRONMENT:**

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Google Chrome 55.0.2883.79 / Safari on Ipod Touch 5 gen
- OS/Platform (with version) I'm using: iOS 9.3.4
- I use latest [tangram](https://github.com/tangrams/tangram) for WebGL map (vector tiles)
- I use latest leaflet-routing-machine: 3.2.4

**OTHER:**

Screenshots: http://imgur.com/a/n6EiW
The first picture is no zoom, in the second picture using pinch zoom. You should pay attention that the marker remains in the right place. But the line moves across the screen.

Leaflet said that the bug is likely not on their side https://github.com/Leaflet/Leaflet/issues/5205

**Comment by bcamper** [comment]
Strange - thanks, we'll take a look (hopefully soon, but not sure due to holidays)!

**Comment by bcamper** [comment]
Hi - here's what I found so far:

1. Tangram currently has an issue keeping itself in sync with layers that are CSS-animated in Leaflet. This is related to Tangram's view being a single map-size Canvas element that does not use CSS for zoom animations. For this reason, it **forces the `zoomAnimation` option to `false`**, which is the source of the problem here. We should look for better ways to maintain a correct view when `zoomAnimation` is `true` (which it is by default), and I'll keep this issue open for that.

2. However, I noticed that Leaflet itself also doesn't seem to mix this overlay layer with a plain raster layer well when `zoomAnimation: false`. Here's the plain-OSM example showing the same pinch-zoom issue: https://jsfiddle.net/a5007q4c/2/

I'll update this issue with Tangram-related fixes.

**Comment by wotgl** [comment]
Thanks, I will wait for news!

1. Yes, `zoomAnimation: false` doesn`t solve the problem.
2. I experimented with versions and noticed, if you select Leaflet version 0.7.7, the lines behave correctly: scale and moving around the map. But there occurs another problem - the map itself does not dynamically react to the pinch zoom. The change of scale happens only after removed fingers from the screen

**Comment by bcamper** [comment]
@wotgl I think I have a fix in a branch, available at:
https://precog.mapzen.com/tangrams/tangram/viewreset/dist/tangram.debug.js

Could you check this updated test pointing to the new branch and confirm if it looks right to you?
https://jsfiddle.net/a5007q4c/3/

**Comment by wotgl** [comment]
@bcamper Yes, it works correctly!
Thanks for the fix and happy new year 2017!)

**Comment by bcamper** [comment]
Released in [v0.11.7](https://github.com/tangrams/tangram/releases/tag/v0.11.7)
