### ISSUE TITLE
How to show GeoJSON data using tangram?

### ISSUE THREAD

**Issue by shahidnawazkhan** [tangrams/tangram#479]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- List the steps you used
Just like we add as a source I add tried to add the GeoJSON to tangram as shown below:
sources:
    mysource:
        type: GeoJSON
        url: http://localhost:8080/geoserver/PakistanRoads/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=PakistanRoads%3APAK_roads&maxFeatures=50&outputformat=application%2Fjson
        max_zoom: 16

The URL is Roads data coming from Geoserver. 
- **To produce the result here**
The Data is roads data of Pakistan and I should see the roads on the map but they aren't there. 

**RESULT:**
Nothing is shown on my map

**EXPECTED RESULT:**

I expect the road to be on the map which aren't.

**ENVIRONMENT:**

I am running it on Windows Localhost

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

**Comment by nvkelso** [comment]
@shahidnawazkhan are you getting 50 features shown on the map, or none at all? You may also need to specify a projection?

**Comment by shahidnawazkhan** [comment]
I am not getting any single feature shown. In previous example provided there was no projection defined anywhere. And if I've to define the projection where and how it can be.

**Comment by shahidnawazkhan** [comment]
The projection is also mentioned if we see the GeoJSON file which EPSG4326

**Comment by nvkelso** [comment]
Is there a public version of the source we could test with (not on
localhost)?

**Comment by shahidnawazkhan** [comment]
No. Actually, the data is roads of Pakistan available public in shape file which i have loaded to postgis. Now i want to show that using tangram.

**Comment by meetar** [comment]
Hello @shahidnawazkhan – we'll need some more information from you solve this.

1) Are there any error messages shown in the console?
2) Are you able to share the JSON with us? Even just the first few lines would be helpful, so that we can ensure the format of the JSON matches what Tangram is expecting.
3) Can you share your scenefile with us?

**Comment by am2222** [comment]
Hi @meetar 

I have the same problem too,It is very strange. It loads shape on chrome but not in opera. It is absolutely something wrong with json but I cant figure out what's wrong. When at first I use 6161.json opera, mobile browser and chrome shows it great. But when I change it to azad.json only chrome
 desktop shows. What could make this problem?

I have attached both json files and ymal file. Can you please take a look at them?

[uu.zip](https://github.com/tangrams/tangram/files/705415/uu.zip)

**Comment by am2222** [comment]
https://github.com/tangrams/tangram/issues/461
It seems these problems are some how related,isn't is?

**Comment by meetar** [comment]
Hi @am2222 – I don't think this is related to #461, which has to do with loading JSON from a javascript variable. It could be a character set problem, however in your case it seems you have very small, detailed, and overlapping geometry. Tangram is designed for basemap creation and display of large-scale features, and other uses may not behave as expected.

If you still have questions, please open a new issue. Thanks!

**Comment by am2222** [comment]
@meetar  thanks for your help, So you mean tangram is not a good choose for for sth like indoor maps?
I have defined the source using javascript in this code
`		$.getJSON('../GFpishroShopping/getmap.php?buildingid='+mallID+'&buildingfloorid='+MallFloor, function (json) {
		layer.scene.setDataSource('dynamic_data', { type: 'GeoJSON', data: json});
		
		L.geoJSON(json.points, {
				
				pointToLayer: function (feature, latlng) {
					var p = L.icon.mapkey({icon:feature.properties.icon,color:'#725139',background:'#f2c357',size:30});
					return L.marker(latlng,{icon: p}).addTo(map).on('click', onMarkerClick);
				}
		}).addTo(map);	
		

		
	});
Can you please explain a bit more about this? "Tangram is designed for basemap creation and display of large-scale features, " so if my geometry has overlaps and details I might face problems?why it is related to scale?If it is necessary should I create a new issue for this question?

**Comment by meetar** [comment]
@am2222 If your features are very small, client-side processes may introduce invalid geometry because some part of the stack ran out of significant digits. After further investigation this doesn't seem to be the case with Tangram, we have your source drawing fine here in Chrome as well – though you might try setting `max_zoom: 20` on your datasource's `source` entry, as in this example: 

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fc53748a707fd3eaa97b983487451091a%2Fraw%2F48d82484063bd10b4ca8699b34c8c7b8f23bb3d4%2Fscene.yaml#20.00000/35.74981/51.57332

Please also note that we haven't tested Tangram on Opera and can't offer support for it at this time.

If you still have questions, please open a new issue, as this is unrelated to the current thread. Thanks!
