### ISSUE TITLE
Error rendering icons on tangram map

### ISSUE THREAD

**Issue by bozzwin** [tangrams/tangram#495]
I am writing a simple web application base on Angular 2. Inside the app I included tangram to visualize some data with icons.  For the first time, when the page is loaded, the data and icons are generated properly, but when I switch to second page and back to page with map, the icons disappearing on the map. In console I getting some warning, like below:

**.Offscreen-For-WebGL-000000001313D040]RENDER WARNING: there is no texture bound to the unit 0**

**Before:**
![1](https://cloud.githubusercontent.com/assets/1229003/22852922/d1a2ce92-f047-11e6-942c-e131de93134a.png)

**After:**
![2](https://cloud.githubusercontent.com/assets/1229003/22852923/d576a138-f047-11e6-8c3f-6ad1d7c503d5.png)

Anyone know how to resolve this issue?

**Comment by bcamper** [comment]
Huh that is an unusual one. We have seen that error caused in other cases, but there are no known outstanding examples.

To clarify:
- Do you mean you are navigating to another route within a single-page app, but not making an additional server-side request or reloading the window?
- What is the file source for the icons? Is it a resource from a remote server, or something like a blob URL or your application, or HTML element?

Are you able to provide access to your app for testing?

Thanks!

**Comment by bozzwin** [comment]
Regarding the first point, yes I am navigating to another route within a single-page app using RouterModule. When I was trying to navigate using `<li><a href="/list">List</a></li> `instead of `<li><a [routerLink]="['/list']">List</a></li>`, the page reloaded and the icons appeared.

About second point. It doesn't matter what kind of source file for icons I set up. I have tried in a different way. Whenever I changed it, the result is always the same.

- textures:
    icon:
        url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA'

- textures:
    icon:
        url: icon.png

- textures:
    icon:
        url: http://localhost:9090/getIcon

Thanks

**Comment by bcamper** [comment]
Hi, I believe there must be something about the environment (Angular or otherwise) that is presenting previously unseen behavior in Tangram. Is it possible for you to expose a version of your app for debugging? If you prefer to send to me privately, let me know. I am afraid it may be hard to debug otherwise.

**Comment by bozzwin** [comment]
@bcamper I have already sent to you my example. I do not now if your email is correct: bcamper@alum.mit.edu

**Comment by bcamper** [comment]
Aha! It went to spam :/ Thanks, we'll take a look when we can.

**Comment by bcamper** [comment]
Hi - It looks like the component with the map is re-initialized each time the user switches to that tab. This means that multiple Tangram maps are being created, but the previous ones are not being cleaned up. I was able to get your example to work by adding a hook that cleans up the map (using Leaflet's [`remove()`](http://leafletjs.com/reference-1.0.3.html) method) on component destroy (in `welcome.component.ts`):

```
    ngOnDestroy() {
        this.leafletMap.remove();
        this.leafletMap = null;
        this.layerTangram = null;
    }
```

Can you give this a try on your full app to verify if it works for you?

(Side note, part of the problem here is globally managed resources in Tangram that should be properly separated; we will follow up on improving that, however even in that case, you wouldn't want to create several maps without cleaning up the old ones within the same user session.)

**Comment by bozzwin** [comment]
Hi, Thanks for your suggestion. Now it is working fine.
