### ISSUE TITLE
Question about fading between zoom levels and fractional $zoom?

### ISSUE THREAD

**Issue by subblue** [tangrams/tangram#530]
My question might be due to my current limited understanding on how the rendering is performed in Tangram...

Is it is possible to blend between styles when zooming, or at least fade in/out text labels at certain zoom thresholds? 

I had tried setting a function on the font.size property thinking that I could get the size to change as I zoomed, but it seems that the $zoom parameter is only the integer zoom level and not the fractional zoom. 
I also tried setting font.fill colours at different zoom levels hoping they might blend between different zooms, but they change abruptly at each zoom boundary.

Is this due to the fact the styles are only calculated once per zoom level and fractional zoom related styling for fading etc would require the styles to be updated far more often?

Thanks for any insight!

**Comment by bcamper** [comment]
You are correct that the styling specified in the scene YAML only applies at integer zooms. The background on that is each integer zoom corresponds to a tile level of detail, so for each zoom, new tile data is loaded (with geometry that is pre-simplified for the appropriate on-screen scale for that zoom). WebGL VBOs are then built for each tile zoom, and the color (and other style) info is baked into these buffers.

An exception is that line widths *do* smoothly interpolate across zooms, which is done with an extra vertex attribute specifying the width's rate of change of the zoom (so that it smoothly connects with the next/previous tile zoom). The same technique *could* be applied to color, it's mostly a tradeoff of VBO memory consumption. But it's something we could consider as an option, perhaps (it might be undesirable in some cases for traditional cartography if the color interpolation is too muddy). I am less sure how well it would work with text due to possible bitmap scaling artifacts, but it's also something we could try (and has been requested :).

While not yet released, we are also considering providing the ability for users to specify *custom vertex attributes*, which would allow someone to implement this with our [shader extensions](https://mapzen.com/documentation/tangram/shaders/#shaders) within the scene YAML.

In the meantime, if you were willing to bake some assumptions into your rendering style (which could be specified with custom [uniforms](https://mapzen.com/documentation/tangram/shaders/#uniforms) or [defines](https://mapzen.com/documentation/tangram/shaders/#defines)). You can use the built-in [`u_map_position.z`](https://mapzen.com/documentation/tangram/shaders/#built-in-uniforms) uniform to access the current fractional view zoom, and could for example modulate the pixel's color (or for text, alpha fade) in the [`filter`](https://mapzen.com/documentation/tangram/shaders/#filter) shader block.

Feel free to drop other implementation thoughts or wishlist items :)

**Comment by subblue** [comment]
Thanks, that is a great help! 
I think a filter shader block looks like it might do some of the things I'm going for.

**Comment by dmvaldman** [comment]
I can only hope you plan to make an infinitely zoomable fractal world with Tangram :-)

**Comment by subblue** [comment]
Haha, with the project I'm working on the real world is plenty enough ;-)

**Comment by bcamper** [comment]
Closing for now, feel free to reopen or open a new issue if you have more questions.
