### ISSUE TITLE
modifyScrollWheel behavior

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#554]
Hi, I dont want to use default fractional zooming so I am using modifyScrollWheel set to false. The thing is when its set to false, when I zoom the tangram layer content is like quickly jumping between zoom levels, which is little bit undesirable.

![modifyscrollwheel](https://cloud.githubusercontent.com/assets/15179841/25608381/e6b9e1c8-2f1a-11e7-8c9e-20b4fa242436.gif)

In version 0.11.6 its working fine, without content jumping: 
![modifyscrollwheel2](https://cloud.githubusercontent.com/assets/15179841/25608600/c52650f4-2f1b-11e7-95d8-a47e7ace7d15.gif)

Is it possible to somehow get it working like in 0.11.6?

**Comment by meetar** [comment]
Hi @michaelhornak! For clarification, the lines and points are the Tangram layer, and there's a raster layer behind it (looks like Positron), right? Are you layering the raster layer behind the vector data as a separate Leaflet layer, or as a raster layer in Tangram?

In the top gif it looks like Tangram is jumping between whole integer zoom levels, but the raster layer is still using fractional zooms, or possibly animating between zooms. Is your goal to have the raster layer jump like the vector layer, or for the vector layer to animate like the raster layer?

And lastly: do you happen to have an example scene we can check out? If not we can likely set one up here.

**Comment by michaelhornak** [comment]
Hi, yes, lines and points are Tangram layer. The positron raster is a separate Leaflet layer. In both examples I have set in map modifyScrollWheel to false. My goal is to have raster jump like the vector like in the second example. 

There is example site to a first gif [http://flww_tangram2.ai-maps.com/](http://flww_tangram2.ai-maps.com/)
There is example site to a second gif [http://flww_tangram.ai-maps.com/](http://flww_tangram.ai-maps.com/)

**Comment by bcamper** [comment]
Hi @michaelhornak, thanks for the examples.

I believe what's happening here is that Leaflet is applying CSS transitions (for the zoom animation) to your raster layer. Tangram can't use CSS transitions (since it's a WebGL canvas) and I haven't yet found a good way to link the Tangram view to a Leaflet CSS animation (but it warrants further research).

In the meantime, I think you can achieve your desired results by setting `zoomAnimation: false` option on your *Leaflet map* instance (not a Tangram layer setting):
http://leafletjs.com/reference-1.0.3.html#map-zoomanimation

The reason you see a difference with the older Tangram version is that we used to force-disable Leaflet animations on the whole map (for this and other issues), but concluded it is better to not force the modification of map-wide parameters where possible. Incidentally, you also likely do not need to have the Tangram option `modifyScrollWheel: false`, I believe it should be a separate issue from what you are experiencing with Leaflet zoom animations. It shouldn't hurt anything either though.

**Comment by michaelhornak** [comment]
thanks very much, this is all I 've needed!
