### ISSUE TITLE
Webpack bundling tangram error

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#559]
Hi, 

As I've read, since tangram  v0.12 it is possible to bundle tangram.js with other scripts. We are using import to load tangram.js and then bundle it with all other scripts to vendors.js file. 

When the app starts, I am consoling Tangram variable to see if its visible. Console prints it ok so Tangram is avaliable to the app.  But right after that i got two errors: 

![tangram_error](https://cloud.githubusercontent.com/assets/15179841/26098687/d2d7951a-3a28-11e7-8f65-aebdbfa31335.png)
![tangram_error2](https://cloud.githubusercontent.com/assets/15179841/26098713/e3f8387c-3a28-11e7-9244-c86b4b254349.png)

In this scenario, scene doesnt load and the map is blank with no data.

When I add tangram.js in the index.html everything works fine, scene loads and I can see all data rendered.

Do you have any clue what could be wrong in my first scenario with bundling approach?

Thanks very much.

**Comment by bcamper** [comment]
Hi @michaelhornak - can you let us know what bundling tools you are using here? 

@louh and I are investigating what looks like the same issue with Webpack bundling (Browserify works).

**Comment by michaelhornak** [comment]
yep, it could be the same issue, we are also using Webpack

**Comment by bcamper** [comment]
Thanks - I'm not that familiar with Webpack so need to dig in more, but it appears to be an issue with Webpack rewriting (?) this condition in the module source:

`if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}`

to

`if(true){module.exports=f()}`

Which is what you see failing in your screen above. This is because this code is being executed in a web worker and neither `module` nor `exports` is defined. Perhaps there's a hint we need to give Webpack to avoid removing that conditional for this code.

**Comment by louh** [comment]
Hi @michaelhornak,

There's a couple of workarounds we need in `webpack.config.js` right now to get around this issue. It's not pretty, but it's necessary at the moment.

The first workaround is to tell Webpack not to parse the Tangram library using the [`noParse`](https://webpack.js.org/configuration/module/#module-noparse) on Tangram. See here: https://github.com/tangrams/react-webpack-tangram-boilerplate/blob/master/webpack.config.js#L30-L31

The second workaround is only required in production bundling (when you optimize/minify). We need to create a separate UglifyJS plugin configuration and turn off the `comparisons` option. See here: https://github.com/tangrams/react-webpack-tangram-boilerplate/blob/master/webpack.config.js#L9-L16

Hope that helps!

**Comment by michaelhornak** [comment]
Thanks guys! workaround is working 👍

**Comment by bcamper** [comment]
With Tangram v0.12.5, released last week, you no longer need to create a custom UglifyJS plugin for use with Wepback.

You do however still need the `noParse` option applied to Tangram (for now anyway). We will continue to look at ways to mitigate this.

**Comment by mparaniak** [comment]
I would like to confirm this workaround is indeed working. I had the exact same errors. 
It was not easy to find it though, and I would suggest changing [Advanced Tangram](https://github.com/tangrams/tangram-play/wiki/Advanced-Tangram-for-front-end-engineers:-bundlers,-frameworks,-etc) to explicitly say for use with webpack the above workarounds are needed.

**Comment by meetar** [comment]
Thanks very much for the feedback! We intend to have more examples of bundling soon.
cc @louh

**Comment by louh** [comment]
Thanks for the confirmation, @mparaniak. The canonical reference for a Webpack-based build is located in this repository: https://github.com/tangrams/react-webpack-tangram-boilerplate/

Hopefully this is more useful because one can actually grab the code and run it to make sure it works. I'll update the wiki in the meantime to point to this.

**Comment by ruatara** [comment]
Anyone got tests working on a project with bundled tangram?  I'm not executing tangram code from any of my tests, it fails on import running this code:

`var __worker_src__ = arguments.callee.toString();var __worker_src_origin__ = typeof document !== "undefined" && document.currentScript !== undefined ? document.currentScript.src : ''`

**Comment by meetar** [comment]
Hi @ruatara – is this an issue with a Webpack bundle? If so, are you using the boilerplate outlined at https://github.com/tangrams/react-webpack-tangram-boilerplate/ ?

**Comment by ruatara** [comment]
I'm not using that boilerplate.  I am using the no-parse option and my app works fine with tangram bundled, the tests don't run ( from command line, in node) though.  looks like it runs some code when the module is resolved.

**Comment by bcamper** [comment]
@ruatara hmm.. yes, that code runs at module import to allow Tangram to reference its own source code, for web worker creation. If I recall, it is one of the reasons the `noParse` option was needed in Webpack.

What is your testing setup? I admit I don't think we have any internal projects that are running tests against a Webpack build Tangram build, and I'm not familiar with testing in Webpack. @rfriberg might have some thoughts.

**Comment by bcamper** [comment]
@ruatara would you be able to tell me if this build has the same issue for you?

https://precog.mapzen.com/tangrams/tangram/webworkify/dist/tangram.min.js

**Comment by ruatara** [comment]
Sorry, super slow response but yes that build works for me.

**Comment by TheCuda** [comment]
This problem still exists. I wanted to try out Tangram for a project of my employer and I can't even run the simplest configuration because of the same error:

```
Uncaught ReferenceError: module is not defined

(anonymous) @ blob:http://127.0.0.…95e5-b0682c72896c:1
(anonymous) @ blob:http://127.0.0.…95e5-b0682c72896c:1
(anonymous) @ blob:http://127.0.0.…5e5-b0682c72896c:20
```

The noParse entry in the webpack.config.js doesn't seem to work. 
Neither do the boilerplates ([webpack-tangram-boilerplate](https://github.com/tangrams/webpack-tangram-boilerplate) and [react-webpack-tangram-boilerplate](https://github.com/tangrams/react-webpack-tangram-boilerplate)) work. They throw the same error in spite of the noParse option.

Any suggestions?

**Comment by meetar** [comment]
@TheCuda Thanks for the report! https://github.com/tangrams/webpack-tangram-boilerplate was indeed broken thanks to some outdated libraries, I've updated it and it's working for me now.

However I'm not having any trouble building Tangram or the https://github.com/tangrams/react-webpack-tangram-boilerplate repo… could you confirm that you're working with the latest master, and then describe the steps you're taking to produce these errors?

**Comment by TheCuda** [comment]
@meetar I'm using the latest npm package of Tangram (_0.15.1_) and webpack (_4.8.3_) in combination with babel-core (_6.26.3_), babel-loader (_7.1.4_) and babel-preset-env (_1.7.0_) (and some other packages for css, images and so on).

I'm using an identical copy of the [react-webpack-tangram-boilerplate](https://github.com/tangrams/react-webpack-tangram-boilerplate) webpack configuration for testing:

```
const webpack = require('webpack');
const path = require('path');

module.exports = {
  context: path.resolve(__dirname, 'src'),
  entry: {
    entry: './app.js'
  },
  output: {
    path: path.resolve(__dirname, 'dist/scripts'),
    publicPath: 'dist/',
    filename: 'bundle.js'
  },
  module: {
    // Apply `noParse` to Tangram to prevent mangling of UMD boilerplate
    noParse: /tangram\/dist\/tangram/,
    rules: [
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'src'),
        use: [{
          loader: 'babel-loader',
          options: {
            presets: [
              ['env', { modules: false }]
            ]
          }
        }]
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        // This is required to bundle images in Leaflet's stylesheet.
        test: /\.png$/,
        use: 'url-loader'
      }
    ],
  }
};
```

The only difference is that I'm not using React.

I've now found out that I only get `Uncaught ReferenceError: module is not defined` when I use the CLI command `webpack --mode=development --debug --progress`. However removing the `--mode=development` doesn't help that much, because it just changes the ReferenceError to `t is not defined`.

`ReferenceError: module is not defined` points out to this line:

```
function(f) {
  if(true) {
    module.exports=f()
  } else { 
    var g; 
  }
}
```

`ReferenceError: t is not defined` points out to this line:

```
t.exports = function t(e, n, i) {
  function o(a, u) {
    if (!n[a]) {
      if (!e[a]) {
        var l = "function" == typeof r && r;
        if (!u && l)
          return r(a, !0);
        if (s)
          return s(a, !0);
        var c = new Error("Cannot find module '" + a + "'");
        throw c.code = "MODULE_NOT_FOUND",c
      }
      var f = n[a] = {
        exports: {}
      };
      e[a][0].call(f.exports, function(t) {
        var n = e[a][1][t];
        return o(n || t)
      }, f, f.exports, t, e, n, i)
    }
    return n[a].exports
  }
  for (var s = "function" == typeof r && r, a = 0; a < i.length; a++)
    o(i[a]);
  return o
}
```

I've updated my clone of the [webpack-tangram-boilerplate](https://github.com/tangrams/webpack-tangram-boilerplate) and followed the same instructions. Here I get `ReferenceError: e is not defined`.

I've absolutely no idea why it's not working on my machine.

**Comment by meetar** [comment]
@TheCuda Sorry you're having trouble – to clarify, are you having trouble with building the boilerplate repos themselves, or with the webpack.config.js files taken from those repos? In other words, are you able to build those repos separately?

You might also try upgrading npm and node, what do you see if you run:
```
npm --version
node --version
```
?

**Comment by TheCuda** [comment]
@meetar This issue relates to the repos as well as to a custom project with the webpack.config.js from the react-webpack-tangram-boilerplate repo.

If I bundle the react-webpack-tangram-boilerplate and open it in the browser, I get `Uncaught ReferenceError: module is not defined`.

Doing the same with the updated webpack-tangram-boilerplate shows `Uncauhgt ReferenceError: e is not defined`.

I've used node `9.5.0` and npm `6.0.0-next.0`. I also updated node to version `10.1.0` and npm to `6.0.1` (currently the latest versions) and tried to build the boilerplates again. Still the same errors.

I even downgraded both (node to `8.11.2` and npm to `5.8.0`), still no changes. 
I have no clue what's going on here.

**Comment by meetar** [comment]
@TheCuda If you get the chance, could you please paste the entire result from performing those commands with the webpack-tangram-boilerplate repo, ideally starting with a fresh clone?

**Comment by TheCuda** [comment]
@meetar I grabed a trainee and his workstation and we tried to bundle the boilerplate on his machine, too. Here we've the same problem: webpack is bundling everything, but seems to ignore the noParse option. The trainee also works with Windows 10.

My guess: It seems to be a problem with the Windows 10 / webpack combination. This seems to be the most plausible explanation. Agree?

**Comment by meetar** [comment]
Windows! I should have asked for your environment details sooner :) Try updating the noParse line with:

`noParse: /tangram\\dist\\tangram/`

**Comment by TheCuda** [comment]
I should have mentioned it in my first comment *facepalm*

Thanks for the hint. Now it works :)
