### ISSUE TITLE
Loading scene files from data/blob urls, pre-loaded string

### ISSUE THREAD

**Issue by Climax777** [tangrams/tangram#565]
Hi this is a feature request.

I'm trying to embed tangram with leaflet inside a C# WinForms application. The problem is that loading the scene file from cross-domain (ajax) is not supported with the WebBrowser control, which is probably also true for other use cases.

If it could be done to support loading the scene file from a blob/data url or even a pre-loaded string it would be a workaround for the issue.

**Comment by bcamper** [comment]
Hi @Climax777 - you should have a couple options for this:

1. You should be able to convert your string to a blob URL yourself with `window.createObjectURL()`, and then feed it to Tangram.

2. Likely easier, you can directly give Tangram a JS object (rather than a string) to load.

In either case, you may have to account for the lack of a base path to resolve any relative resources against. You could make any resource paths in the scene absolute, or, you could .zip the scene and resources, and use `window.createObjectURL()` to send the entire .zip to Tangram.

**Comment by Climax777** [comment]
Hi @bcamper 

I have a plunker [here](http://plnkr.co/edit/0SpkRzxUdLwQJ7G080Ze?p=preview) which tests the scenario. I can't get it to load the zip from the base64 zip file. Somehow it doesn't accept it as zip, because it tries to parse it as yaml.

Is there some way I can force it to load it as a zip?

**Comment by bcamper** [comment]
Ohh... right, sorry, forgot that it tries to detect .zip via extension (currently anyway) :)

Have you tried the option of just sending a JS object?

**Comment by Climax777** [comment]
The problem with that is the remote referenced assets would still be broken
due to the cross origin issue. How would I convert the yaml to json
anyways?

Would it be possible to implement a type override option in the
constructor?

**Comment by bcamper** [comment]
Yes it's not difficult to add a format override... just will have to wait for a release. We can go ahead and do that though, this case has come up before.

**Comment by Climax777** [comment]
That would be excellent. Please let me know how I can help out.

**Comment by bcamper** [comment]
This will be addressed in #572 and released in the upcoming v0.13.0 release.

**Comment by Climax777** [comment]
Thanks a million!

**Comment by bcamper** [comment]
Released in [v0.13.0](https://github.com/tangrams/tangram/releases/tag/v0.13.0)
