### ISSUE TITLE
Help in understanding build/quine.js 

### ISSUE THREAD

**Issue by agenthunt** [tangrams/tangram#579]
I am trying to understand this particular file [ build/quine.js ](https://github.com/tangrams/tangram/blob/8d49f81a5492d5ddb0b51ec8973895f8c08b1175/build/quine.js#L1) 
Could anyone explain the intent of this ? Is this the helper code to make it run in web workers ?

**Comment by bcamper** [comment]
Yes, it's related to Tangram needing to access the source code of itself in order to instantiate its web workers. It's a somewhat unusual requirement. `quine.js` hooks into the Browserify build process to add some code to enable this. We may also look at other build strategies in the future.

There is some background here:
https://github.com/tangrams/tangram/issues/252

And here:
https://github.com/tangrams/tangram/pull/499
