### ISSUE TITLE
Add support for complex properties from MVT formats

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram#581]
Tangram JS sister issue to https://github.com/tangrams/tangram-es/issues/1618. Related to the root cause of https://github.com/tangrams/tangram-es/issues/1616.

While GeoJSON and TopoJSON support complex property values (nested properties, lists, etc) those are currently dropped in Tilezen MVT format on the server. We plan to add support for stringifying those property values instead in https://github.com/tilezen/mapbox-vector-tile/issues/94.

This Tangram JS issue covers turning the stringified values back into regular complex property as the tile is parsed.

**Comment by matteblair** [comment]
I have concerns about encoding JSON values into MVT string properties. Mainly, the question I have is: How does the engine know which string values should be interpreted as JSON? Possible answers:

 - **Try to parse every string value as JSON**: This is wasteful because the vast majority of string values are not intended to be JSON, and we would also get false positives for string values that can be validly interpreted as JSON (`true`, `null`, etc.).
 - **Use a whitelist of property names to parse as JSON**: This doesn't align with the data-agnostic spirit of Tangram, plus we'd have to change/version this list if the property names ever changed.
 - **Lazily parse properties as JSON if members are accessed**: For instance if a JS function accessed `[0]` or `.a` of a property, we could parse the string value as JSON in our proxy object before returning a value - though this is getting complicated and it still wouldn't behave exactly the same as Tangram JS would.

**Comment by matteblair** [comment]
There are other conceptual solutions to this as well, such as interpreting all feature properties from all formats as JSON values, but that involves more dramatic refactoring.

**Comment by bcamper** [comment]
I agree that knowing which fields to apply extra parsing to is problematic. One thought I had is a variation of your options above, which is that these fields would have to be specified as part of the Tangram data source definition in `sources`. This requires an extra "mini schema" definition step, but stays agnostic.

**Comment by matteblair** [comment]
Ah oops, I meant to post my replies to https://github.com/tangrams/tangram-es/issues/1618 - lots of similar issues in my tabs haha. I suppose the concern still mostly applies here as well.

**Comment by bcamper** [comment]
Support for these properties was added to Tangram JS in https://github.com/tangrams/tangram/releases/tag/v0.19.0. The user must whitelist the MVT properties to be parsed as JSON, or opt into all being parsed and incur a performance hit. No parsing is done by default.

**Comment by nvkelso** [comment]
Huzzah!
