### ISSUE TITLE
Idle optimization

### ISSUE THREAD

**Issue by dv343** [tangrams/tangram#586]
I'm trying to measure and improve, if necessary, Tangram performance, I used chrome's dev tools to get some information.

The first thing that I've noticed is that tangram (in tangram-play at least), keeps using CPU/GPU even when everything is loaded.

Chrome's dev tools shows some small, yet periodic, JS calls, and some, not so small, GPU usage.
I monitored general CPU usage, and the CPU goes up to 45% just by viewing tangram-play (with everything already loaded), in comparison, I get a 4% when the tangram-play tab is not shown.

This is unexpected, and IMO undesired-able. Do you know why tangram does not idle? Is this expected?

If this is not expected I could try to solve it.

Thanks!

**ENVIRONMENT:**

Ubuntu 16.10
Google Chrome 60.0.3112.101

**Comment by bcamper** [comment]
Thanks - could you please try profiling Tangram on its own to get a clearer baseline, using the simple demo (`index.html`) bundled in the repo? Tangram Play has a lot of other moving pieces (Code Mirror, etc.), and also enables some additional Tangram features in some cases (like continuous interactivity feedback) that may influence the profile. (There may also be issues involving Play, but starting with Tangram itself will be simpler.)

There is a continuous loop [`renderLoop()`](https://github.com/tangrams/tangram/blob/master/src/scene.js#L405) run in Tangram via `requestAnimationFrame`, which in turn calls [`update()`](https://github.com/tangrams/tangram/blob/master/src/scene.js#L434). The `update()` method does update/check some things each frame, but I wouldn't expect those to be at 45% CPU :) 

It should only call the more intensive `render()` method (that makes WebGL/GPU calls) if the scene needs to be re-rendered due to a view/interaction change, or an on-going animation, which can be transient (e.g. a label fade-in that stops after ~100ms), but *can also require continuous re-rendering per frame* if the scene is marked as animated.

A scene is considered animated if any of its rendering `styles` have the [`animated`](https://mapzen.com/documentation/tangram/styles/#animated) property set to true; *or*, if the [`scene.animated`](https://mapzen.com/documentation/tangram/scene/#animated) property is set, it will override the style animations (to either force animation on or off). 

Unfortunately, I just realized that some of the example styles in the bundled demo *are* animated, so to get an idle benchmark, you can override the scene to turn animation off:

Either in `scene.yaml`:
```
scene:
   animated: false
```

Or at run-time:
```
scene.config.scene.animated = false;
scene.updateConfig();
```

It may be undesirable for the default demo to be animated anyway, so we can revisit that, and also can improve the animation checking such that it only animates if animated styles are *currently visible* (the demo is not animated by default, but includes some animated styles that can be enabled by the GUI; Tangram currently considers the scene as animated if it includes *any* style definitions that are animated, regardless of whether they are in use).

**Comment by bcamper** [comment]
Re: the logic about about scene animated state, I have updated it in master (not released yet) to only treat the scene as animating when animated styles are *in view* (or when the `scene.animated` property is set to override it): 38d780e854d6536fa63e4f25295742da031d6c7a

**Comment by bcamper** [comment]
Feel free to re-open (or open a new issue) with specifics.
