### ISSUE TITLE
[Question] Indoor maps using Tangram

### ISSUE THREAD

**Issue by HQarroum** [tangrams/tangram#630]
I am creating this issue in order to ask a simple question to Tangram users and developers. I am working on an indoor management prototype and would like to implement indoor floor plans on top of Tangram.

I've spent countless hours documenting myself on GIS in general, and I like the fact that Tangram relies on TopoJSON vector with client rendering (which will allow me to build live floor plans based on live telemetry data, and customize the interior based on different scene files).

**What I've done so far**

I read the Tangram documentation, and got familiar with Tangram.js (scene files, layers, etc.), and I built a new layer based on GeoJSON data representing my floor with the rooms, areas, pois, etc.

**My questions**

How would you recommend to implement live indoor mapping using Tangram, while using TopoJSON (I need to represent complex shapes such as desks, chairs, or amenities which are not possible to describe in GeoJSON) ?

Am I completely in the wrong direction wanting to use Tangram for such purpose (I didn't really find examples addressing indoor maps) ?

Would you recommend using tiled TopoJSON vectors to represent an indoor map (since some buildings may be quite massive and large) ?

Thank you for reading, and for your help.

**Comment by meetar** [comment]
Hello @HQarroum! Tangram, GeoJSON, and TopoJSON are all intended for displaying geographic information, and using it to encode 3D objects like buildings is a kind of "hack" which is already stretching the capabilities of the format. So it's entirely possible to use it for things like building walls and pois, but you'll run into difficulty with other kinds of objects – for instance I wouldn't recommend it for things like stairs, windows, or furniture, not least because to my knowledge there aren't any editors which convert between arbitrary 3D objects and GeoJSON/TopoJSON, and texturing wouldn't be supported regardless.

We'd like to be able to add arbitrary 3D objects to a scene file, but we don't have that capability now, and Geo/TopoJSON isn't the right format for that regardless – we'd probably use something simple like OBJ to start with.

Regarding tiling: Tangram tiles single-file datasources on the fly, so pre-tiling is only really necessary if you're seeing performance issues with an untiled datasource, either on the download or drawing stages . So I recommend you try it without pre-tiling first, and you can always do it afterward if you're not getting the performance you need.

**Comment by HQarroum** [comment]
Thanks @meetar for your quick reply and for your answers! I've put some feedback below in response to your answers.

_"not least because to my knowledge there aren't any editors which convert between arbitrary 3D objects and GeoJSON/TopoJSON"_ **Absolutely**, that's indeed one of the major pain points, exporting from a CAD format for instance to GeoJSON using georeferenced data seems _very_ complex for beginners. I wouldn't need complex things like texturing, but more things like icons for pois, or colors for room types, such as what Google Maps for Indoors already provides.

_"We'd like to be able to add arbitrary 3D objects to a scene file, but we don't have that capability now, and Geo/TopoJSON isn't the right format for that regardless."_ Yes I agree, that's also my sentiment. One of my initial idea was to use SVG instead of TopoJSON + Tangram, to represent complex shapes while still keeping the relevant metadata required for client-side additional layers rendering. I don't know if you have any feedback about this?

"Tangram tiles single-file datasources on the fly". Awesome, good to know!

**Comment by meetar** [comment]
> exporting from a CAD format for instance to GeoJSON using georeferenced data seems very complex for beginners
I'll go so far as to say it would be complex for anybody, and I'd recommend some other kind of solution.

> use SVG instead
Sure, this could work – here's a demo showing a way to generate SVG based on TopoJSON tiles, using d3.js: https://github.com/mapzen/d3-vector-tiles
