### ISSUE TITLE
Ends of linear rings are not joined

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram#631]
So while playing around with shaders (from tron), I came across this situation:

![circle2](https://user-images.githubusercontent.com/4661658/35630859-b36c0520-06a2-11e8-8fb5-2bf8ed5ac921.png)

Check this tangram play setup for a minimal demo:
[**>> Demo <<**](https://tangram.city/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fe4b6909facde8cb6cbff3f44625339b1%2Fraw%2Ffb5105eb015ee678248acab99d3e9b34dfbe0b9e%2Fscene.yaml#20.00000/53.55052/9.97208)

So, the problem is that the start/end of a linear ring is not joined, at least of a `boundary: true`. There is an open end like this, which is especially visible of course if the boundary is not a solid color:

![illust](https://user-images.githubusercontent.com/4661658/35630184-0680fdda-06a1-11e8-954b-f216059f5495.png)

The same issue occurs in [Tangram-ES](https://github.com/tangrams/tangram-es/issues/1765).

**Comment by bcamper** [comment]
Is the underlying data of type linestring, or polygon? If it's a
linestring, this is expected, and it's more of a data issue IMO (though we
could potentially have a draw-group-level option to treat a closed
linestring like this as as polygon). If it's a polygon, then it's not what
I would expect.

**Comment by westnordost** [comment]
It is a polygon. This is the place: https://www.openstreetmap.org/way/461574471

**Comment by bcamper** [comment]
Sorry for the delay. I think the issue is that your `boundary: true` geometries are encoded as a line type in your MVT. Tangram will only draw a closed line on a polygon type. But you do have the polygon version of that geometry in your tiles already -- if you just remove `boundary: true` from the filter, it will draw a line stroke around the same water area you are filling blue, and it should work fine:

```
        shore_lines:
            filter: { $zoom: { min: 16 } }
```

![screen shot 2018-04-22 at 10 40 26 am](https://user-images.githubusercontent.com/16733/39096116-996f7a4c-4619-11e8-8145-06ba26582c9a.png)

**Comment by westnordost** [comment]
True, removing `boundary: true` changes _something_, however the original problem as described remains the same. See here:

![linejoin](https://user-images.githubusercontent.com/4661658/39096333-d81cd598-464e-11e8-812f-56e674c75e71.png)

**Comment by bcamper** [comment]
Ah OK I think the problem is now it's drawing lines styles for *both* boundary (lines) and non-boundary (polygon) features. I think it's working as you want if you explicitly exclude the boundaries?

```
        shore_lines:
            filter: { boundary: false, $zoom: { min: 16 } }
            draw:
                lines-coast:
                    order: global.sort_rank
                    width: 20px
                    color: global.water_color
```

![screen shot 2018-04-22 at 12 43 57 pm](https://user-images.githubusercontent.com/16733/39097505-0b53edd0-462b-11e8-96a0-1c801f6c1a1c.png)

**Comment by westnordost** [comment]
Oh yeah, exactly! That's beautiful, thank you :-D
