### ISSUE TITLE
lines re-render on zooming in

### ISSUE THREAD

**Issue by AnandSrini** [tangrams/tangram#738]
**TANGRAM VERSION:** 0.19.1

**ENVIRONMENT:**

Windows 10, Chrome (79.0.3945.79 (Official Build) (64-bit))

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

yaml configuration for line width:
```
                width: |
                    function() { 
                        return $zoom / 12 * $meters_per_pixel; 
                    }
```

- Render lines from a vector tile source on low zoom level
![fat-zoom-lines](https://user-images.githubusercontent.com/32294324/70901817-83795d00-2021-11ea-82eb-b7de9093017d.png)

- Zoom in to a high zoom level on the lines
![fat-lines](https://user-images.githubusercontent.com/32294324/70901836-896f3e00-2021-11ea-863c-379cc044b54d.png)

**RESULT:**
- The lines will be resized, only after the next set of tiles are loaded
![thin-lines](https://user-images.githubusercontent.com/32294324/70901870-9db33b00-2021-11ea-827a-e033ec45bdc8.png)

**EXPECTED RESULT:**
It would be really nice if the the lines were re-rendered to a smaller size based on the zoom level (while the tiles are being loaded). Like how it happens for circle/polygons.

**Comment by bcamper** [comment]
Thanks - this is overall intentional behavior, but your example shows the worst-case scenario. Tangram's lines are meant to smoothly interpolate width from one zoom level to the next. When you go +/-1 zoom levels out from the current tiles, it has to "guess" how big they will be at the new zoom (since that data is not loaded yet, as you mentioned), and it caps how much the lines are scaled relative to the current zoom. In the past, we had the opposite problem and the lines were sometimes very thin when scaled up several zooms like this. In any case, I do agree that we could revisit these parameters to see if a better balance is possible.

**Comment by AnandSrini** [comment]
But, shapes drawn on points seem to re-draw smoothly even before the data is being loaded.

They are small, but you can notice small squares at the end of the lines. They are re-sized before the tiles are loaded, but lines are not.

Is there something that I am missing?

![image](https://user-images.githubusercontent.com/32294324/72250470-a8152480-3621-11ea-8b48-395a020e9a49.png)


![image](https://user-images.githubusercontent.com/32294324/72250487-b105f600-3621-11ea-8dab-a4216d946147.png)

![image](https://user-images.githubusercontent.com/32294324/72250613-fe826300-3621-11ea-9123-97be70665298.png)

**Comment by bcamper** [comment]
Sorry, can you explain more what you mean about the shapes drawn on the points? Are those other geometries you are generating in your scene file? Or are you only drawing lines, and observing those "extra" lines when changing zooms? If the latter, it's possible you are seeing the old and new tiles rendering simultaneously for some time, as the old tiles will continue to draw to cover the space until all necessary new tiles have loaded (and one old tile from a lower zoom could cover many tiles from a new higher zoom). Does that make sense?

**Comment by bcamper** [comment]
Working as expected.
